// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mcpserver

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"

	"github.com/GilmanLab/agentcompute/internal/compute"
)

// NewMocksandboxService creates a new instance of MocksandboxService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMocksandboxService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MocksandboxService {
	mock := &MocksandboxService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MocksandboxService is an autogenerated mock type for the sandboxService type
type MocksandboxService struct {
	mock.Mock
}

type MocksandboxService_Expecter struct {
	mock *mock.Mock
}

func (_m *MocksandboxService) EXPECT() *MocksandboxService_Expecter {
	return &MocksandboxService_Expecter{mock: &_m.Mock}
}

// CreateSandbox provides a mock function for the type MocksandboxService
func (_mock *MocksandboxService) CreateSandbox(ctx context.Context, name string, ttl time.Duration, subject string) (compute.Sandbox, error) {
	ret := _mock.Called(ctx, name, ttl, subject)

	if len(ret) == 0 {
		panic("no return value specified for CreateSandbox")
	}

	var r0 compute.Sandbox
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration, string) (compute.Sandbox, error)); ok {
		return returnFunc(ctx, name, ttl, subject)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration, string) compute.Sandbox); ok {
		r0 = returnFunc(ctx, name, ttl, subject)
	} else {
		r0 = ret.Get(0).(compute.Sandbox)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Duration, string) error); ok {
		r1 = returnFunc(ctx, name, ttl, subject)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MocksandboxService_CreateSandbox_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSandbox'
type MocksandboxService_CreateSandbox_Call struct {
	*mock.Call
}

// CreateSandbox is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - ttl time.Duration
//   - subject string
func (_e *MocksandboxService_Expecter) CreateSandbox(ctx any, name any, ttl any, subject any) *MocksandboxService_CreateSandbox_Call {
	return &MocksandboxService_CreateSandbox_Call{Call: _e.mock.On("CreateSandbox", ctx, name, ttl, subject)}
}

func (_c *MocksandboxService_CreateSandbox_Call) Run(run func(ctx context.Context, name string, ttl time.Duration, subject string)) *MocksandboxService_CreateSandbox_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MocksandboxService_CreateSandbox_Call) Return(sandbox compute.Sandbox, err error) *MocksandboxService_CreateSandbox_Call {
	_c.Call.Return(sandbox, err)
	return _c
}

func (_c *MocksandboxService_CreateSandbox_Call) RunAndReturn(run func(ctx context.Context, name string, ttl time.Duration, subject string) (compute.Sandbox, error)) *MocksandboxService_CreateSandbox_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSandbox provides a mock function for the type MocksandboxService
func (_mock *MocksandboxService) DeleteSandbox(ctx context.Context, name string) error {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSandbox")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MocksandboxService_DeleteSandbox_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSandbox'
type MocksandboxService_DeleteSandbox_Call struct {
	*mock.Call
}

// DeleteSandbox is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MocksandboxService_Expecter) DeleteSandbox(ctx any, name any) *MocksandboxService_DeleteSandbox_Call {
	return &MocksandboxService_DeleteSandbox_Call{Call: _e.mock.On("DeleteSandbox", ctx, name)}
}

func (_c *MocksandboxService_DeleteSandbox_Call) Run(run func(ctx context.Context, name string)) *MocksandboxService_DeleteSandbox_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MocksandboxService_DeleteSandbox_Call) Return(err error) *MocksandboxService_DeleteSandbox_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MocksandboxService_DeleteSandbox_Call) RunAndReturn(run func(ctx context.Context, name string) error) *MocksandboxService_DeleteSandbox_Call {
	_c.Call.Return(run)
	return _c
}

// ExtendSandbox provides a mock function for the type MocksandboxService
func (_mock *MocksandboxService) ExtendSandbox(ctx context.Context, name string, ttl time.Duration) (compute.Sandbox, error) {
	ret := _mock.Called(ctx, name, ttl)

	if len(ret) == 0 {
		panic("no return value specified for ExtendSandbox")
	}

	var r0 compute.Sandbox
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration) (compute.Sandbox, error)); ok {
		return returnFunc(ctx, name, ttl)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration) compute.Sandbox); ok {
		r0 = returnFunc(ctx, name, ttl)
	} else {
		r0 = ret.Get(0).(compute.Sandbox)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Duration) error); ok {
		r1 = returnFunc(ctx, name, ttl)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MocksandboxService_ExtendSandbox_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExtendSandbox'
type MocksandboxService_ExtendSandbox_Call struct {
	*mock.Call
}

// ExtendSandbox is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - ttl time.Duration
func (_e *MocksandboxService_Expecter) ExtendSandbox(ctx any, name any, ttl any) *MocksandboxService_ExtendSandbox_Call {
	return &MocksandboxService_ExtendSandbox_Call{Call: _e.mock.On("ExtendSandbox", ctx, name, ttl)}
}

func (_c *MocksandboxService_ExtendSandbox_Call) Run(run func(ctx context.Context, name string, ttl time.Duration)) *MocksandboxService_ExtendSandbox_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MocksandboxService_ExtendSandbox_Call) Return(sandbox compute.Sandbox, err error) *MocksandboxService_ExtendSandbox_Call {
	_c.Call.Return(sandbox, err)
	return _c
}

func (_c *MocksandboxService_ExtendSandbox_Call) RunAndReturn(run func(ctx context.Context, name string, ttl time.Duration) (compute.Sandbox, error)) *MocksandboxService_ExtendSandbox_Call {
	_c.Call.Return(run)
	return _c
}

// GetSandbox provides a mock function for the type MocksandboxService
func (_mock *MocksandboxService) GetSandbox(ctx context.Context, name string) (compute.Sandbox, []compute.Instance, []compute.Network, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetSandbox")
	}

	var r0 compute.Sandbox
	var r1 []compute.Instance
	var r2 []compute.Network
	var r3 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (compute.Sandbox, []compute.Instance, []compute.Network, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) compute.Sandbox); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(compute.Sandbox)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) []compute.Instance); ok {
		r1 = returnFunc(ctx, name)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]compute.Instance)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) []compute.Network); ok {
		r2 = returnFunc(ctx, name)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).([]compute.Network)
		}
	}
	if returnFunc, ok := ret.Get(3).(func(context.Context, string) error); ok {
		r3 = returnFunc(ctx, name)
	} else {
		r3 = ret.Error(3)
	}
	return r0, r1, r2, r3
}

// MocksandboxService_GetSandbox_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSandbox'
type MocksandboxService_GetSandbox_Call struct {
	*mock.Call
}

// GetSandbox is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MocksandboxService_Expecter) GetSandbox(ctx any, name any) *MocksandboxService_GetSandbox_Call {
	return &MocksandboxService_GetSandbox_Call{Call: _e.mock.On("GetSandbox", ctx, name)}
}

func (_c *MocksandboxService_GetSandbox_Call) Run(run func(ctx context.Context, name string)) *MocksandboxService_GetSandbox_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MocksandboxService_GetSandbox_Call) Return(sandbox compute.Sandbox, instances []compute.Instance, networks []compute.Network, err error) *MocksandboxService_GetSandbox_Call {
	_c.Call.Return(sandbox, instances, networks, err)
	return _c
}

func (_c *MocksandboxService_GetSandbox_Call) RunAndReturn(run func(ctx context.Context, name string) (compute.Sandbox, []compute.Instance, []compute.Network, error)) *MocksandboxService_GetSandbox_Call {
	_c.Call.Return(run)
	return _c
}

// ListSandboxes provides a mock function for the type MocksandboxService
func (_mock *MocksandboxService) ListSandboxes(ctx context.Context) ([]compute.Sandbox, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListSandboxes")
	}

	var r0 []compute.Sandbox
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]compute.Sandbox, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []compute.Sandbox); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]compute.Sandbox)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MocksandboxService_ListSandboxes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSandboxes'
type MocksandboxService_ListSandboxes_Call struct {
	*mock.Call
}

// ListSandboxes is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MocksandboxService_Expecter) ListSandboxes(ctx any) *MocksandboxService_ListSandboxes_Call {
	return &MocksandboxService_ListSandboxes_Call{Call: _e.mock.On("ListSandboxes", ctx)}
}

func (_c *MocksandboxService_ListSandboxes_Call) Run(run func(ctx context.Context)) *MocksandboxService_ListSandboxes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MocksandboxService_ListSandboxes_Call) Return(sandboxs []compute.Sandbox, err error) *MocksandboxService_ListSandboxes_Call {
	_c.Call.Return(sandboxs, err)
	return _c
}

func (_c *MocksandboxService_ListSandboxes_Call) RunAndReturn(run func(ctx context.Context) ([]compute.Sandbox, error)) *MocksandboxService_ListSandboxes_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockinstanceService creates a new instance of MockinstanceService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockinstanceService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockinstanceService {
	mock := &MockinstanceService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockinstanceService is an autogenerated mock type for the instanceService type
type MockinstanceService struct {
	mock.Mock
}

type MockinstanceService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockinstanceService) EXPECT() *MockinstanceService_Expecter {
	return &MockinstanceService_Expecter{mock: &_m.Mock}
}

// CreateInstance provides a mock function for the type MockinstanceService
func (_mock *MockinstanceService) CreateInstance(ctx context.Context, req compute.CreateInstance) (compute.Instance, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateInstance")
	}

	var r0 compute.Instance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, compute.CreateInstance) (compute.Instance, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, compute.CreateInstance) compute.Instance); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(compute.Instance)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, compute.CreateInstance) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockinstanceService_CreateInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInstance'
type MockinstanceService_CreateInstance_Call struct {
	*mock.Call
}

// CreateInstance is a helper method to define mock.On call
//   - ctx context.Context
//   - req compute.CreateInstance
func (_e *MockinstanceService_Expecter) CreateInstance(ctx any, req any) *MockinstanceService_CreateInstance_Call {
	return &MockinstanceService_CreateInstance_Call{Call: _e.mock.On("CreateInstance", ctx, req)}
}

func (_c *MockinstanceService_CreateInstance_Call) Run(run func(ctx context.Context, req compute.CreateInstance)) *MockinstanceService_CreateInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 compute.CreateInstance
		if args[1] != nil {
			arg1 = args[1].(compute.CreateInstance)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockinstanceService_CreateInstance_Call) Return(instance compute.Instance, err error) *MockinstanceService_CreateInstance_Call {
	_c.Call.Return(instance, err)
	return _c
}

func (_c *MockinstanceService_CreateInstance_Call) RunAndReturn(run func(ctx context.Context, req compute.CreateInstance) (compute.Instance, error)) *MockinstanceService_CreateInstance_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteInstance provides a mock function for the type MockinstanceService
func (_mock *MockinstanceService) DeleteInstance(ctx context.Context, ref compute.Ref) error {
	ret := _mock.Called(ctx, ref)

	if len(ret) == 0 {
		panic("no return value specified for DeleteInstance")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, compute.Ref) error); ok {
		r0 = returnFunc(ctx, ref)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockinstanceService_DeleteInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteInstance'
type MockinstanceService_DeleteInstance_Call struct {
	*mock.Call
}

// DeleteInstance is a helper method to define mock.On call
//   - ctx context.Context
//   - ref compute.Ref
func (_e *MockinstanceService_Expecter) DeleteInstance(ctx any, ref any) *MockinstanceService_DeleteInstance_Call {
	return &MockinstanceService_DeleteInstance_Call{Call: _e.mock.On("DeleteInstance", ctx, ref)}
}

func (_c *MockinstanceService_DeleteInstance_Call) Run(run func(ctx context.Context, ref compute.Ref)) *MockinstanceService_DeleteInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 compute.Ref
		if args[1] != nil {
			arg1 = args[1].(compute.Ref)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockinstanceService_DeleteInstance_Call) Return(err error) *MockinstanceService_DeleteInstance_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockinstanceService_DeleteInstance_Call) RunAndReturn(run func(ctx context.Context, ref compute.Ref) error) *MockinstanceService_DeleteInstance_Call {
	_c.Call.Return(run)
	return _c
}

// Exec provides a mock function for the type MockinstanceService
func (_mock *MockinstanceService) Exec(ctx context.Context, req compute.ExecRequest) (compute.ExecResult, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 compute.ExecResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, compute.ExecRequest) (compute.ExecResult, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, compute.ExecRequest) compute.ExecResult); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(compute.ExecResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, compute.ExecRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockinstanceService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockinstanceService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - req compute.ExecRequest
func (_e *MockinstanceService_Expecter) Exec(ctx any, req any) *MockinstanceService_Exec_Call {
	return &MockinstanceService_Exec_Call{Call: _e.mock.On("Exec", ctx, req)}
}

func (_c *MockinstanceService_Exec_Call) Run(run func(ctx context.Context, req compute.ExecRequest)) *MockinstanceService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 compute.ExecRequest
		if args[1] != nil {
			arg1 = args[1].(compute.ExecRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockinstanceService_Exec_Call) Return(execResult compute.ExecResult, err error) *MockinstanceService_Exec_Call {
	_c.Call.Return(execResult, err)
	return _c
}

func (_c *MockinstanceService_Exec_Call) RunAndReturn(run func(ctx context.Context, req compute.ExecRequest) (compute.ExecResult, error)) *MockinstanceService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// GetInstance provides a mock function for the type MockinstanceService
func (_mock *MockinstanceService) GetInstance(ctx context.Context, ref compute.Ref) (compute.Instance, error) {
	ret := _mock.Called(ctx, ref)

	if len(ret) == 0 {
		panic("no return value specified for GetInstance")
	}

	var r0 compute.Instance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, compute.Ref) (compute.Instance, error)); ok {
		return returnFunc(ctx, ref)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, compute.Ref) compute.Instance); ok {
		r0 = returnFunc(ctx, ref)
	} else {
		r0 = ret.Get(0).(compute.Instance)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, compute.Ref) error); ok {
		r1 = returnFunc(ctx, ref)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockinstanceService_GetInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInstance'
type MockinstanceService_GetInstance_Call struct {
	*mock.Call
}

// GetInstance is a helper method to define mock.On call
//   - ctx context.Context
//   - ref compute.Ref
func (_e *MockinstanceService_Expecter) GetInstance(ctx any, ref any) *MockinstanceService_GetInstance_Call {
	return &MockinstanceService_GetInstance_Call{Call: _e.mock.On("GetInstance", ctx, ref)}
}

func (_c *MockinstanceService_GetInstance_Call) Run(run func(ctx context.Context, ref compute.Ref)) *MockinstanceService_GetInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 compute.Ref
		if args[1] != nil {
			arg1 = args[1].(compute.Ref)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockinstanceService_GetInstance_Call) Return(instance compute.Instance, err error) *MockinstanceService_GetInstance_Call {
	_c.Call.Return(instance, err)
	return _c
}

func (_c *MockinstanceService_GetInstance_Call) RunAndReturn(run func(ctx context.Context, ref compute.Ref) (compute.Instance, error)) *MockinstanceService_GetInstance_Call {
	_c.Call.Return(run)
	return _c
}

// ListInstances provides a mock function for the type MockinstanceService
func (_mock *MockinstanceService) ListInstances(ctx context.Context, sandbox string) ([]compute.Instance, error) {
	ret := _mock.Called(ctx, sandbox)

	if len(ret) == 0 {
		panic("no return value specified for ListInstances")
	}

	var r0 []compute.Instance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]compute.Instance, error)); ok {
		return returnFunc(ctx, sandbox)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []compute.Instance); ok {
		r0 = returnFunc(ctx, sandbox)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]compute.Instance)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, sandbox)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockinstanceService_ListInstances_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListInstances'
type MockinstanceService_ListInstances_Call struct {
	*mock.Call
}

// ListInstances is a helper method to define mock.On call
//   - ctx context.Context
//   - sandbox string
func (_e *MockinstanceService_Expecter) ListInstances(ctx any, sandbox any) *MockinstanceService_ListInstances_Call {
	return &MockinstanceService_ListInstances_Call{Call: _e.mock.On("ListInstances", ctx, sandbox)}
}

func (_c *MockinstanceService_ListInstances_Call) Run(run func(ctx context.Context, sandbox string)) *MockinstanceService_ListInstances_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockinstanceService_ListInstances_Call) Return(instances []compute.Instance, err error) *MockinstanceService_ListInstances_Call {
	_c.Call.Return(instances, err)
	return _c
}

func (_c *MockinstanceService_ListInstances_Call) RunAndReturn(run func(ctx context.Context, sandbox string) ([]compute.Instance, error)) *MockinstanceService_ListInstances_Call {
	_c.Call.Return(run)
	return _c
}

// NewMocknetworkService creates a new instance of MocknetworkService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMocknetworkService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MocknetworkService {
	mock := &MocknetworkService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MocknetworkService is an autogenerated mock type for the networkService type
type MocknetworkService struct {
	mock.Mock
}

type MocknetworkService_Expecter struct {
	mock *mock.Mock
}

func (_m *MocknetworkService) EXPECT() *MocknetworkService_Expecter {
	return &MocknetworkService_Expecter{mock: &_m.Mock}
}

// AttachNIC provides a mock function for the type MocknetworkService
func (_mock *MocknetworkService) AttachNIC(ctx context.Context, ref compute.Ref, network string, nic string, ip string, mac string) (compute.NIC, error) {
	ret := _mock.Called(ctx, ref, network, nic, ip, mac)

	if len(ret) == 0 {
		panic("no return value specified for AttachNIC")
	}

	var r0 compute.NIC
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, compute.Ref, string, string, string, string) (compute.NIC, error)); ok {
		return returnFunc(ctx, ref, network, nic, ip, mac)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, compute.Ref, string, string, string, string) compute.NIC); ok {
		r0 = returnFunc(ctx, ref, network, nic, ip, mac)
	} else {
		r0 = ret.Get(0).(compute.NIC)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, compute.Ref, string, string, string, string) error); ok {
		r1 = returnFunc(ctx, ref, network, nic, ip, mac)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MocknetworkService_AttachNIC_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AttachNIC'
type MocknetworkService_AttachNIC_Call struct {
	*mock.Call
}

// AttachNIC is a helper method to define mock.On call
//   - ctx context.Context
//   - ref compute.Ref
//   - network string
//   - nic string
//   - ip string
//   - mac string
func (_e *MocknetworkService_Expecter) AttachNIC(ctx any, ref any, network any, nic any, ip any, mac any) *MocknetworkService_AttachNIC_Call {
	return &MocknetworkService_AttachNIC_Call{Call: _e.mock.On("AttachNIC", ctx, ref, network, nic, ip, mac)}
}

func (_c *MocknetworkService_AttachNIC_Call) Run(run func(ctx context.Context, ref compute.Ref, network string, nic string, ip string, mac string)) *MocknetworkService_AttachNIC_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 compute.Ref
		if args[1] != nil {
			arg1 = args[1].(compute.Ref)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MocknetworkService_AttachNIC_Call) Return(nIC compute.NIC, err error) *MocknetworkService_AttachNIC_Call {
	_c.Call.Return(nIC, err)
	return _c
}

func (_c *MocknetworkService_AttachNIC_Call) RunAndReturn(run func(ctx context.Context, ref compute.Ref, network string, nic string, ip string, mac string) (compute.NIC, error)) *MocknetworkService_AttachNIC_Call {
	_c.Call.Return(run)
	return _c
}

// CreateNetwork provides a mock function for the type MocknetworkService
func (_mock *MocknetworkService) CreateNetwork(ctx context.Context, sandbox string, network compute.Network) (compute.Network, error) {
	ret := _mock.Called(ctx, sandbox, network)

	if len(ret) == 0 {
		panic("no return value specified for CreateNetwork")
	}

	var r0 compute.Network
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, compute.Network) (compute.Network, error)); ok {
		return returnFunc(ctx, sandbox, network)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, compute.Network) compute.Network); ok {
		r0 = returnFunc(ctx, sandbox, network)
	} else {
		r0 = ret.Get(0).(compute.Network)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, compute.Network) error); ok {
		r1 = returnFunc(ctx, sandbox, network)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MocknetworkService_CreateNetwork_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateNetwork'
type MocknetworkService_CreateNetwork_Call struct {
	*mock.Call
}

// CreateNetwork is a helper method to define mock.On call
//   - ctx context.Context
//   - sandbox string
//   - network compute.Network
func (_e *MocknetworkService_Expecter) CreateNetwork(ctx any, sandbox any, network any) *MocknetworkService_CreateNetwork_Call {
	return &MocknetworkService_CreateNetwork_Call{Call: _e.mock.On("CreateNetwork", ctx, sandbox, network)}
}

func (_c *MocknetworkService_CreateNetwork_Call) Run(run func(ctx context.Context, sandbox string, network compute.Network)) *MocknetworkService_CreateNetwork_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 compute.Network
		if args[2] != nil {
			arg2 = args[2].(compute.Network)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MocknetworkService_CreateNetwork_Call) Return(network1 compute.Network, err error) *MocknetworkService_CreateNetwork_Call {
	_c.Call.Return(network1, err)
	return _c
}

func (_c *MocknetworkService_CreateNetwork_Call) RunAndReturn(run func(ctx context.Context, sandbox string, network compute.Network) (compute.Network, error)) *MocknetworkService_CreateNetwork_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockimageService creates a new instance of MockimageService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockimageService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockimageService {
	mock := &MockimageService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockimageService is an autogenerated mock type for the imageService type
type MockimageService struct {
	mock.Mock
}

type MockimageService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockimageService) EXPECT() *MockimageService_Expecter {
	return &MockimageService_Expecter{mock: &_m.Mock}
}

// CatalogImage provides a mock function for the type MockimageService
func (_mock *MockimageService) CatalogImage(name string) (compute.CatalogImage, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for CatalogImage")
	}

	var r0 compute.CatalogImage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (compute.CatalogImage, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) compute.CatalogImage); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Get(0).(compute.CatalogImage)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockimageService_CatalogImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CatalogImage'
type MockimageService_CatalogImage_Call struct {
	*mock.Call
}

// CatalogImage is a helper method to define mock.On call
//   - name string
func (_e *MockimageService_Expecter) CatalogImage(name any) *MockimageService_CatalogImage_Call {
	return &MockimageService_CatalogImage_Call{Call: _e.mock.On("CatalogImage", name)}
}

func (_c *MockimageService_CatalogImage_Call) Run(run func(name string)) *MockimageService_CatalogImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockimageService_CatalogImage_Call) Return(catalogImage compute.CatalogImage, err error) *MockimageService_CatalogImage_Call {
	_c.Call.Return(catalogImage, err)
	return _c
}

func (_c *MockimageService_CatalogImage_Call) RunAndReturn(run func(name string) (compute.CatalogImage, error)) *MockimageService_CatalogImage_Call {
	_c.Call.Return(run)
	return _c
}

// ListImages provides a mock function for the type MockimageService
func (_mock *MockimageService) ListImages(os string, desktop *bool, platform string) []compute.CatalogImage {
	ret := _mock.Called(os, desktop, platform)

	if len(ret) == 0 {
		panic("no return value specified for ListImages")
	}

	var r0 []compute.CatalogImage
	if returnFunc, ok := ret.Get(0).(func(string, *bool, string) []compute.CatalogImage); ok {
		r0 = returnFunc(os, desktop, platform)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]compute.CatalogImage)
		}
	}
	return r0
}

// MockimageService_ListImages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListImages'
type MockimageService_ListImages_Call struct {
	*mock.Call
}

// ListImages is a helper method to define mock.On call
//   - os string
//   - desktop *bool
//   - platform string
func (_e *MockimageService_Expecter) ListImages(os any, desktop any, platform any) *MockimageService_ListImages_Call {
	return &MockimageService_ListImages_Call{Call: _e.mock.On("ListImages", os, desktop, platform)}
}

func (_c *MockimageService_ListImages_Call) Run(run func(os string, desktop *bool, platform string)) *MockimageService_ListImages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *bool
		if args[1] != nil {
			arg1 = args[1].(*bool)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockimageService_ListImages_Call) Return(catalogImages []compute.CatalogImage) *MockimageService_ListImages_Call {
	_c.Call.Return(catalogImages)
	return _c
}

func (_c *MockimageService_ListImages_Call) RunAndReturn(run func(os string, desktop *bool, platform string) []compute.CatalogImage) *MockimageService_ListImages_Call {
	_c.Call.Return(run)
	return _c
}
