// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"
	"time"

	mock "github.com/stretchr/testify/mock"

	"github.com/GilmanLab/agentcompute/internal/compute"
)

// NewMockBackend creates a new instance of MockBackend. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBackend(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBackend {
	mock := &MockBackend{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBackend is an autogenerated mock type for the Backend type
type MockBackend struct {
	mock.Mock
}

type MockBackend_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBackend) EXPECT() *MockBackend_Expecter {
	return &MockBackend_Expecter{mock: &_m.Mock}
}

// AttachNIC provides a mock function for the type MockBackend
func (_mock *MockBackend) AttachNIC(context1 context.Context, ref compute.Ref, s string, s1 string, s2 string, s3 string) (compute.NIC, error) {
	ret := _mock.Called(context1, ref, s, s1, s2, s3)

	if len(ret) == 0 {
		panic("no return value specified for AttachNIC")
	}

	var r0 compute.NIC
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, compute.Ref, string, string, string, string) (compute.NIC, error)); ok {
		return returnFunc(context1, ref, s, s1, s2, s3)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, compute.Ref, string, string, string, string) compute.NIC); ok {
		r0 = returnFunc(context1, ref, s, s1, s2, s3)
	} else {
		r0 = ret.Get(0).(compute.NIC)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, compute.Ref, string, string, string, string) error); ok {
		r1 = returnFunc(context1, ref, s, s1, s2, s3)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackend_AttachNIC_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AttachNIC'
type MockBackend_AttachNIC_Call struct {
	*mock.Call
}

// AttachNIC is a helper method to define mock.On call
//   - context1 context.Context
//   - ref compute.Ref
//   - s string
//   - s1 string
//   - s2 string
//   - s3 string
func (_e *MockBackend_Expecter) AttachNIC(context1 any, ref any, s any, s1 any, s2 any, s3 any) *MockBackend_AttachNIC_Call {
	return &MockBackend_AttachNIC_Call{Call: _e.mock.On("AttachNIC", context1, ref, s, s1, s2, s3)}
}

func (_c *MockBackend_AttachNIC_Call) Run(run func(context1 context.Context, ref compute.Ref, s string, s1 string, s2 string, s3 string)) *MockBackend_AttachNIC_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 compute.Ref
		if args[1] != nil {
			arg1 = args[1].(compute.Ref)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockBackend_AttachNIC_Call) Return(nIC compute.NIC, err error) *MockBackend_AttachNIC_Call {
	_c.Call.Return(nIC, err)
	return _c
}

func (_c *MockBackend_AttachNIC_Call) RunAndReturn(run func(context1 context.Context, ref compute.Ref, s string, s1 string, s2 string, s3 string) (compute.NIC, error)) *MockBackend_AttachNIC_Call {
	_c.Call.Return(run)
	return _c
}

// BeginCreateInstance provides a mock function for the type MockBackend
func (_mock *MockBackend) BeginCreateInstance(context1 context.Context, createInstance compute.CreateInstance) (compute.PendingInstance, error) {
	ret := _mock.Called(context1, createInstance)

	if len(ret) == 0 {
		panic("no return value specified for BeginCreateInstance")
	}

	var r0 compute.PendingInstance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, compute.CreateInstance) (compute.PendingInstance, error)); ok {
		return returnFunc(context1, createInstance)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, compute.CreateInstance) compute.PendingInstance); ok {
		r0 = returnFunc(context1, createInstance)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(compute.PendingInstance)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, compute.CreateInstance) error); ok {
		r1 = returnFunc(context1, createInstance)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackend_BeginCreateInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginCreateInstance'
type MockBackend_BeginCreateInstance_Call struct {
	*mock.Call
}

// BeginCreateInstance is a helper method to define mock.On call
//   - context1 context.Context
//   - createInstance compute.CreateInstance
func (_e *MockBackend_Expecter) BeginCreateInstance(context1 any, createInstance any) *MockBackend_BeginCreateInstance_Call {
	return &MockBackend_BeginCreateInstance_Call{Call: _e.mock.On("BeginCreateInstance", context1, createInstance)}
}

func (_c *MockBackend_BeginCreateInstance_Call) Run(run func(context1 context.Context, createInstance compute.CreateInstance)) *MockBackend_BeginCreateInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 compute.CreateInstance
		if args[1] != nil {
			arg1 = args[1].(compute.CreateInstance)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBackend_BeginCreateInstance_Call) Return(pendingInstance compute.PendingInstance, err error) *MockBackend_BeginCreateInstance_Call {
	_c.Call.Return(pendingInstance, err)
	return _c
}

func (_c *MockBackend_BeginCreateInstance_Call) RunAndReturn(run func(context1 context.Context, createInstance compute.CreateInstance) (compute.PendingInstance, error)) *MockBackend_BeginCreateInstance_Call {
	_c.Call.Return(run)
	return _c
}

// CreateNetwork provides a mock function for the type MockBackend
func (_mock *MockBackend) CreateNetwork(context1 context.Context, s string, network compute.Network) (compute.Network, error) {
	ret := _mock.Called(context1, s, network)

	if len(ret) == 0 {
		panic("no return value specified for CreateNetwork")
	}

	var r0 compute.Network
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, compute.Network) (compute.Network, error)); ok {
		return returnFunc(context1, s, network)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, compute.Network) compute.Network); ok {
		r0 = returnFunc(context1, s, network)
	} else {
		r0 = ret.Get(0).(compute.Network)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, compute.Network) error); ok {
		r1 = returnFunc(context1, s, network)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackend_CreateNetwork_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateNetwork'
type MockBackend_CreateNetwork_Call struct {
	*mock.Call
}

// CreateNetwork is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - network compute.Network
func (_e *MockBackend_Expecter) CreateNetwork(context1 any, s any, network any) *MockBackend_CreateNetwork_Call {
	return &MockBackend_CreateNetwork_Call{Call: _e.mock.On("CreateNetwork", context1, s, network)}
}

func (_c *MockBackend_CreateNetwork_Call) Run(run func(context1 context.Context, s string, network compute.Network)) *MockBackend_CreateNetwork_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 compute.Network
		if args[2] != nil {
			arg2 = args[2].(compute.Network)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBackend_CreateNetwork_Call) Return(network1 compute.Network, err error) *MockBackend_CreateNetwork_Call {
	_c.Call.Return(network1, err)
	return _c
}

func (_c *MockBackend_CreateNetwork_Call) RunAndReturn(run func(context1 context.Context, s string, network compute.Network) (compute.Network, error)) *MockBackend_CreateNetwork_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSandbox provides a mock function for the type MockBackend
func (_mock *MockBackend) CreateSandbox(context1 context.Context, sandbox compute.Sandbox) error {
	ret := _mock.Called(context1, sandbox)

	if len(ret) == 0 {
		panic("no return value specified for CreateSandbox")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, compute.Sandbox) error); ok {
		r0 = returnFunc(context1, sandbox)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBackend_CreateSandbox_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSandbox'
type MockBackend_CreateSandbox_Call struct {
	*mock.Call
}

// CreateSandbox is a helper method to define mock.On call
//   - context1 context.Context
//   - sandbox compute.Sandbox
func (_e *MockBackend_Expecter) CreateSandbox(context1 any, sandbox any) *MockBackend_CreateSandbox_Call {
	return &MockBackend_CreateSandbox_Call{Call: _e.mock.On("CreateSandbox", context1, sandbox)}
}

func (_c *MockBackend_CreateSandbox_Call) Run(run func(context1 context.Context, sandbox compute.Sandbox)) *MockBackend_CreateSandbox_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 compute.Sandbox
		if args[1] != nil {
			arg1 = args[1].(compute.Sandbox)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBackend_CreateSandbox_Call) Return(err error) *MockBackend_CreateSandbox_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBackend_CreateSandbox_Call) RunAndReturn(run func(context1 context.Context, sandbox compute.Sandbox) error) *MockBackend_CreateSandbox_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteInstance provides a mock function for the type MockBackend
func (_mock *MockBackend) DeleteInstance(context1 context.Context, ref compute.Ref) error {
	ret := _mock.Called(context1, ref)

	if len(ret) == 0 {
		panic("no return value specified for DeleteInstance")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, compute.Ref) error); ok {
		r0 = returnFunc(context1, ref)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBackend_DeleteInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteInstance'
type MockBackend_DeleteInstance_Call struct {
	*mock.Call
}

// DeleteInstance is a helper method to define mock.On call
//   - context1 context.Context
//   - ref compute.Ref
func (_e *MockBackend_Expecter) DeleteInstance(context1 any, ref any) *MockBackend_DeleteInstance_Call {
	return &MockBackend_DeleteInstance_Call{Call: _e.mock.On("DeleteInstance", context1, ref)}
}

func (_c *MockBackend_DeleteInstance_Call) Run(run func(context1 context.Context, ref compute.Ref)) *MockBackend_DeleteInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 compute.Ref
		if args[1] != nil {
			arg1 = args[1].(compute.Ref)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBackend_DeleteInstance_Call) Return(err error) *MockBackend_DeleteInstance_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBackend_DeleteInstance_Call) RunAndReturn(run func(context1 context.Context, ref compute.Ref) error) *MockBackend_DeleteInstance_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSandbox provides a mock function for the type MockBackend
func (_mock *MockBackend) DeleteSandbox(context1 context.Context, s string) error {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSandbox")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBackend_DeleteSandbox_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSandbox'
type MockBackend_DeleteSandbox_Call struct {
	*mock.Call
}

// DeleteSandbox is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockBackend_Expecter) DeleteSandbox(context1 any, s any) *MockBackend_DeleteSandbox_Call {
	return &MockBackend_DeleteSandbox_Call{Call: _e.mock.On("DeleteSandbox", context1, s)}
}

func (_c *MockBackend_DeleteSandbox_Call) Run(run func(context1 context.Context, s string)) *MockBackend_DeleteSandbox_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBackend_DeleteSandbox_Call) Return(err error) *MockBackend_DeleteSandbox_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBackend_DeleteSandbox_Call) RunAndReturn(run func(context1 context.Context, s string) error) *MockBackend_DeleteSandbox_Call {
	_c.Call.Return(run)
	return _c
}

// Exec provides a mock function for the type MockBackend
func (_mock *MockBackend) Exec(context1 context.Context, execRequest compute.ExecRequest, writer io.Writer, writer1 io.Writer) (int64, error) {
	ret := _mock.Called(context1, execRequest, writer, writer1)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, compute.ExecRequest, io.Writer, io.Writer) (int64, error)); ok {
		return returnFunc(context1, execRequest, writer, writer1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, compute.ExecRequest, io.Writer, io.Writer) int64); ok {
		r0 = returnFunc(context1, execRequest, writer, writer1)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, compute.ExecRequest, io.Writer, io.Writer) error); ok {
		r1 = returnFunc(context1, execRequest, writer, writer1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackend_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockBackend_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - context1 context.Context
//   - execRequest compute.ExecRequest
//   - writer io.Writer
//   - writer1 io.Writer
func (_e *MockBackend_Expecter) Exec(context1 any, execRequest any, writer any, writer1 any) *MockBackend_Exec_Call {
	return &MockBackend_Exec_Call{Call: _e.mock.On("Exec", context1, execRequest, writer, writer1)}
}

func (_c *MockBackend_Exec_Call) Run(run func(context1 context.Context, execRequest compute.ExecRequest, writer io.Writer, writer1 io.Writer)) *MockBackend_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 compute.ExecRequest
		if args[1] != nil {
			arg1 = args[1].(compute.ExecRequest)
		}
		var arg2 io.Writer
		if args[2] != nil {
			arg2 = args[2].(io.Writer)
		}
		var arg3 io.Writer
		if args[3] != nil {
			arg3 = args[3].(io.Writer)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockBackend_Exec_Call) Return(n int64, err error) *MockBackend_Exec_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockBackend_Exec_Call) RunAndReturn(run func(context1 context.Context, execRequest compute.ExecRequest, writer io.Writer, writer1 io.Writer) (int64, error)) *MockBackend_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// ExtendSandbox provides a mock function for the type MockBackend
func (_mock *MockBackend) ExtendSandbox(context1 context.Context, s string, time1 time.Time) (compute.Sandbox, error) {
	ret := _mock.Called(context1, s, time1)

	if len(ret) == 0 {
		panic("no return value specified for ExtendSandbox")
	}

	var r0 compute.Sandbox
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) (compute.Sandbox, error)); ok {
		return returnFunc(context1, s, time1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) compute.Sandbox); ok {
		r0 = returnFunc(context1, s, time1)
	} else {
		r0 = ret.Get(0).(compute.Sandbox)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = returnFunc(context1, s, time1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackend_ExtendSandbox_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExtendSandbox'
type MockBackend_ExtendSandbox_Call struct {
	*mock.Call
}

// ExtendSandbox is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - time1 time.Time
func (_e *MockBackend_Expecter) ExtendSandbox(context1 any, s any, time1 any) *MockBackend_ExtendSandbox_Call {
	return &MockBackend_ExtendSandbox_Call{Call: _e.mock.On("ExtendSandbox", context1, s, time1)}
}

func (_c *MockBackend_ExtendSandbox_Call) Run(run func(context1 context.Context, s string, time1 time.Time)) *MockBackend_ExtendSandbox_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBackend_ExtendSandbox_Call) Return(sandbox compute.Sandbox, err error) *MockBackend_ExtendSandbox_Call {
	_c.Call.Return(sandbox, err)
	return _c
}

func (_c *MockBackend_ExtendSandbox_Call) RunAndReturn(run func(context1 context.Context, s string, time1 time.Time) (compute.Sandbox, error)) *MockBackend_ExtendSandbox_Call {
	_c.Call.Return(run)
	return _c
}

// GetInstance provides a mock function for the type MockBackend
func (_mock *MockBackend) GetInstance(context1 context.Context, ref compute.Ref) (compute.Instance, error) {
	ret := _mock.Called(context1, ref)

	if len(ret) == 0 {
		panic("no return value specified for GetInstance")
	}

	var r0 compute.Instance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, compute.Ref) (compute.Instance, error)); ok {
		return returnFunc(context1, ref)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, compute.Ref) compute.Instance); ok {
		r0 = returnFunc(context1, ref)
	} else {
		r0 = ret.Get(0).(compute.Instance)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, compute.Ref) error); ok {
		r1 = returnFunc(context1, ref)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackend_GetInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInstance'
type MockBackend_GetInstance_Call struct {
	*mock.Call
}

// GetInstance is a helper method to define mock.On call
//   - context1 context.Context
//   - ref compute.Ref
func (_e *MockBackend_Expecter) GetInstance(context1 any, ref any) *MockBackend_GetInstance_Call {
	return &MockBackend_GetInstance_Call{Call: _e.mock.On("GetInstance", context1, ref)}
}

func (_c *MockBackend_GetInstance_Call) Run(run func(context1 context.Context, ref compute.Ref)) *MockBackend_GetInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 compute.Ref
		if args[1] != nil {
			arg1 = args[1].(compute.Ref)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBackend_GetInstance_Call) Return(instance compute.Instance, err error) *MockBackend_GetInstance_Call {
	_c.Call.Return(instance, err)
	return _c
}

func (_c *MockBackend_GetInstance_Call) RunAndReturn(run func(context1 context.Context, ref compute.Ref) (compute.Instance, error)) *MockBackend_GetInstance_Call {
	_c.Call.Return(run)
	return _c
}

// GetSandbox provides a mock function for the type MockBackend
func (_mock *MockBackend) GetSandbox(context1 context.Context, s string) (compute.Sandbox, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for GetSandbox")
	}

	var r0 compute.Sandbox
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (compute.Sandbox, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) compute.Sandbox); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Get(0).(compute.Sandbox)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackend_GetSandbox_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSandbox'
type MockBackend_GetSandbox_Call struct {
	*mock.Call
}

// GetSandbox is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockBackend_Expecter) GetSandbox(context1 any, s any) *MockBackend_GetSandbox_Call {
	return &MockBackend_GetSandbox_Call{Call: _e.mock.On("GetSandbox", context1, s)}
}

func (_c *MockBackend_GetSandbox_Call) Run(run func(context1 context.Context, s string)) *MockBackend_GetSandbox_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBackend_GetSandbox_Call) Return(sandbox compute.Sandbox, err error) *MockBackend_GetSandbox_Call {
	_c.Call.Return(sandbox, err)
	return _c
}

func (_c *MockBackend_GetSandbox_Call) RunAndReturn(run func(context1 context.Context, s string) (compute.Sandbox, error)) *MockBackend_GetSandbox_Call {
	_c.Call.Return(run)
	return _c
}

// ListInstances provides a mock function for the type MockBackend
func (_mock *MockBackend) ListInstances(context1 context.Context, s string) ([]compute.Instance, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for ListInstances")
	}

	var r0 []compute.Instance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]compute.Instance, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []compute.Instance); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]compute.Instance)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackend_ListInstances_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListInstances'
type MockBackend_ListInstances_Call struct {
	*mock.Call
}

// ListInstances is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockBackend_Expecter) ListInstances(context1 any, s any) *MockBackend_ListInstances_Call {
	return &MockBackend_ListInstances_Call{Call: _e.mock.On("ListInstances", context1, s)}
}

func (_c *MockBackend_ListInstances_Call) Run(run func(context1 context.Context, s string)) *MockBackend_ListInstances_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBackend_ListInstances_Call) Return(instances []compute.Instance, err error) *MockBackend_ListInstances_Call {
	_c.Call.Return(instances, err)
	return _c
}

func (_c *MockBackend_ListInstances_Call) RunAndReturn(run func(context1 context.Context, s string) ([]compute.Instance, error)) *MockBackend_ListInstances_Call {
	_c.Call.Return(run)
	return _c
}

// ListNetworks provides a mock function for the type MockBackend
func (_mock *MockBackend) ListNetworks(context1 context.Context, s string) ([]compute.Network, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for ListNetworks")
	}

	var r0 []compute.Network
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]compute.Network, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []compute.Network); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]compute.Network)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackend_ListNetworks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListNetworks'
type MockBackend_ListNetworks_Call struct {
	*mock.Call
}

// ListNetworks is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockBackend_Expecter) ListNetworks(context1 any, s any) *MockBackend_ListNetworks_Call {
	return &MockBackend_ListNetworks_Call{Call: _e.mock.On("ListNetworks", context1, s)}
}

func (_c *MockBackend_ListNetworks_Call) Run(run func(context1 context.Context, s string)) *MockBackend_ListNetworks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBackend_ListNetworks_Call) Return(networks []compute.Network, err error) *MockBackend_ListNetworks_Call {
	_c.Call.Return(networks, err)
	return _c
}

func (_c *MockBackend_ListNetworks_Call) RunAndReturn(run func(context1 context.Context, s string) ([]compute.Network, error)) *MockBackend_ListNetworks_Call {
	_c.Call.Return(run)
	return _c
}

// ListSandboxes provides a mock function for the type MockBackend
func (_mock *MockBackend) ListSandboxes(context1 context.Context) ([]compute.Sandbox, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for ListSandboxes")
	}

	var r0 []compute.Sandbox
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]compute.Sandbox, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []compute.Sandbox); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]compute.Sandbox)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackend_ListSandboxes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSandboxes'
type MockBackend_ListSandboxes_Call struct {
	*mock.Call
}

// ListSandboxes is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockBackend_Expecter) ListSandboxes(context1 any) *MockBackend_ListSandboxes_Call {
	return &MockBackend_ListSandboxes_Call{Call: _e.mock.On("ListSandboxes", context1)}
}

func (_c *MockBackend_ListSandboxes_Call) Run(run func(context1 context.Context)) *MockBackend_ListSandboxes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBackend_ListSandboxes_Call) Return(sandboxs []compute.Sandbox, err error) *MockBackend_ListSandboxes_Call {
	_c.Call.Return(sandboxs, err)
	return _c
}

func (_c *MockBackend_ListSandboxes_Call) RunAndReturn(run func(context1 context.Context) ([]compute.Sandbox, error)) *MockBackend_ListSandboxes_Call {
	_c.Call.Return(run)
	return _c
}
