// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"
	"time"

	mock "github.com/stretchr/testify/mock"

	"github.com/GilmanLab/agentcompute/internal/compute"
)

// NewMockBackend creates a new instance of MockBackend. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBackend(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBackend {
	mock := &MockBackend{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBackend is an autogenerated mock type for the Backend type
type MockBackend struct {
	mock.Mock
}

type MockBackend_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBackend) EXPECT() *MockBackend_Expecter {
	return &MockBackend_Expecter{mock: &_m.Mock}
}

// AddACLRule provides a mock function for the type MockBackend
func (_mock *MockBackend) AddACLRule(context1 context.Context, s string, s1 string, aCLRule compute.ACLRule) (compute.ACLRule, error) {
	ret := _mock.Called(context1, s, s1, aCLRule)

	if len(ret) == 0 {
		panic("no return value specified for AddACLRule")
	}

	var r0 compute.ACLRule
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, compute.ACLRule) (compute.ACLRule, error)); ok {
		return returnFunc(context1, s, s1, aCLRule)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, compute.ACLRule) compute.ACLRule); ok {
		r0 = returnFunc(context1, s, s1, aCLRule)
	} else {
		r0 = ret.Get(0).(compute.ACLRule)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, compute.ACLRule) error); ok {
		r1 = returnFunc(context1, s, s1, aCLRule)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackend_AddACLRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddACLRule'
type MockBackend_AddACLRule_Call struct {
	*mock.Call
}

// AddACLRule is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
//   - aCLRule compute.ACLRule
func (_e *MockBackend_Expecter) AddACLRule(context1 interface{}, s interface{}, s1 interface{}, aCLRule interface{}) *MockBackend_AddACLRule_Call {
	return &MockBackend_AddACLRule_Call{Call: _e.mock.On("AddACLRule", context1, s, s1, aCLRule)}
}

func (_c *MockBackend_AddACLRule_Call) Run(run func(context1 context.Context, s string, s1 string, aCLRule compute.ACLRule)) *MockBackend_AddACLRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 compute.ACLRule
		if args[3] != nil {
			arg3 = args[3].(compute.ACLRule)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockBackend_AddACLRule_Call) Return(aCLRule1 compute.ACLRule, err error) *MockBackend_AddACLRule_Call {
	_c.Call.Return(aCLRule1, err)
	return _c
}

func (_c *MockBackend_AddACLRule_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string, aCLRule compute.ACLRule) (compute.ACLRule, error)) *MockBackend_AddACLRule_Call {
	_c.Call.Return(run)
	return _c
}

// AttachNIC provides a mock function for the type MockBackend
func (_mock *MockBackend) AttachNIC(context1 context.Context, ref compute.Ref, s string, s1 string, s2 string, s3 string) (compute.NIC, error) {
	ret := _mock.Called(context1, ref, s, s1, s2, s3)

	if len(ret) == 0 {
		panic("no return value specified for AttachNIC")
	}

	var r0 compute.NIC
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, compute.Ref, string, string, string, string) (compute.NIC, error)); ok {
		return returnFunc(context1, ref, s, s1, s2, s3)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, compute.Ref, string, string, string, string) compute.NIC); ok {
		r0 = returnFunc(context1, ref, s, s1, s2, s3)
	} else {
		r0 = ret.Get(0).(compute.NIC)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, compute.Ref, string, string, string, string) error); ok {
		r1 = returnFunc(context1, ref, s, s1, s2, s3)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackend_AttachNIC_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AttachNIC'
type MockBackend_AttachNIC_Call struct {
	*mock.Call
}

// AttachNIC is a helper method to define mock.On call
//   - context1 context.Context
//   - ref compute.Ref
//   - s string
//   - s1 string
//   - s2 string
//   - s3 string
func (_e *MockBackend_Expecter) AttachNIC(context1 interface{}, ref interface{}, s interface{}, s1 interface{}, s2 interface{}, s3 interface{}) *MockBackend_AttachNIC_Call {
	return &MockBackend_AttachNIC_Call{Call: _e.mock.On("AttachNIC", context1, ref, s, s1, s2, s3)}
}

func (_c *MockBackend_AttachNIC_Call) Run(run func(context1 context.Context, ref compute.Ref, s string, s1 string, s2 string, s3 string)) *MockBackend_AttachNIC_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 compute.Ref
		if args[1] != nil {
			arg1 = args[1].(compute.Ref)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockBackend_AttachNIC_Call) Return(nIC compute.NIC, err error) *MockBackend_AttachNIC_Call {
	_c.Call.Return(nIC, err)
	return _c
}

func (_c *MockBackend_AttachNIC_Call) RunAndReturn(run func(context1 context.Context, ref compute.Ref, s string, s1 string, s2 string, s3 string) (compute.NIC, error)) *MockBackend_AttachNIC_Call {
	_c.Call.Return(run)
	return _c
}

// BeginCreateInstance provides a mock function for the type MockBackend
func (_mock *MockBackend) BeginCreateInstance(context1 context.Context, createInstance compute.CreateInstance) (compute.PendingInstance, error) {
	ret := _mock.Called(context1, createInstance)

	if len(ret) == 0 {
		panic("no return value specified for BeginCreateInstance")
	}

	var r0 compute.PendingInstance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, compute.CreateInstance) (compute.PendingInstance, error)); ok {
		return returnFunc(context1, createInstance)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, compute.CreateInstance) compute.PendingInstance); ok {
		r0 = returnFunc(context1, createInstance)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(compute.PendingInstance)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, compute.CreateInstance) error); ok {
		r1 = returnFunc(context1, createInstance)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackend_BeginCreateInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginCreateInstance'
type MockBackend_BeginCreateInstance_Call struct {
	*mock.Call
}

// BeginCreateInstance is a helper method to define mock.On call
//   - context1 context.Context
//   - createInstance compute.CreateInstance
func (_e *MockBackend_Expecter) BeginCreateInstance(context1 interface{}, createInstance interface{}) *MockBackend_BeginCreateInstance_Call {
	return &MockBackend_BeginCreateInstance_Call{Call: _e.mock.On("BeginCreateInstance", context1, createInstance)}
}

func (_c *MockBackend_BeginCreateInstance_Call) Run(run func(context1 context.Context, createInstance compute.CreateInstance)) *MockBackend_BeginCreateInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 compute.CreateInstance
		if args[1] != nil {
			arg1 = args[1].(compute.CreateInstance)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBackend_BeginCreateInstance_Call) Return(pendingInstance compute.PendingInstance, err error) *MockBackend_BeginCreateInstance_Call {
	_c.Call.Return(pendingInstance, err)
	return _c
}

func (_c *MockBackend_BeginCreateInstance_Call) RunAndReturn(run func(context1 context.Context, createInstance compute.CreateInstance) (compute.PendingInstance, error)) *MockBackend_BeginCreateInstance_Call {
	_c.Call.Return(run)
	return _c
}

// CreateForward provides a mock function for the type MockBackend
func (_mock *MockBackend) CreateForward(context1 context.Context, s string, s1 string, ref compute.Ref, n int64, n1 int64, s2 string) (compute.Forward, error) {
	ret := _mock.Called(context1, s, s1, ref, n, n1, s2)

	if len(ret) == 0 {
		panic("no return value specified for CreateForward")
	}

	var r0 compute.Forward
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, compute.Ref, int64, int64, string) (compute.Forward, error)); ok {
		return returnFunc(context1, s, s1, ref, n, n1, s2)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, compute.Ref, int64, int64, string) compute.Forward); ok {
		r0 = returnFunc(context1, s, s1, ref, n, n1, s2)
	} else {
		r0 = ret.Get(0).(compute.Forward)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, compute.Ref, int64, int64, string) error); ok {
		r1 = returnFunc(context1, s, s1, ref, n, n1, s2)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackend_CreateForward_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateForward'
type MockBackend_CreateForward_Call struct {
	*mock.Call
}

// CreateForward is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
//   - ref compute.Ref
//   - n int64
//   - n1 int64
//   - s2 string
func (_e *MockBackend_Expecter) CreateForward(context1 interface{}, s interface{}, s1 interface{}, ref interface{}, n interface{}, n1 interface{}, s2 interface{}) *MockBackend_CreateForward_Call {
	return &MockBackend_CreateForward_Call{Call: _e.mock.On("CreateForward", context1, s, s1, ref, n, n1, s2)}
}

func (_c *MockBackend_CreateForward_Call) Run(run func(context1 context.Context, s string, s1 string, ref compute.Ref, n int64, n1 int64, s2 string)) *MockBackend_CreateForward_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 compute.Ref
		if args[3] != nil {
			arg3 = args[3].(compute.Ref)
		}
		var arg4 int64
		if args[4] != nil {
			arg4 = args[4].(int64)
		}
		var arg5 int64
		if args[5] != nil {
			arg5 = args[5].(int64)
		}
		var arg6 string
		if args[6] != nil {
			arg6 = args[6].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *MockBackend_CreateForward_Call) Return(forward compute.Forward, err error) *MockBackend_CreateForward_Call {
	_c.Call.Return(forward, err)
	return _c
}

func (_c *MockBackend_CreateForward_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string, ref compute.Ref, n int64, n1 int64, s2 string) (compute.Forward, error)) *MockBackend_CreateForward_Call {
	_c.Call.Return(run)
	return _c
}

// CreateNetwork provides a mock function for the type MockBackend
func (_mock *MockBackend) CreateNetwork(context1 context.Context, s string, network compute.Network) (compute.Network, error) {
	ret := _mock.Called(context1, s, network)

	if len(ret) == 0 {
		panic("no return value specified for CreateNetwork")
	}

	var r0 compute.Network
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, compute.Network) (compute.Network, error)); ok {
		return returnFunc(context1, s, network)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, compute.Network) compute.Network); ok {
		r0 = returnFunc(context1, s, network)
	} else {
		r0 = ret.Get(0).(compute.Network)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, compute.Network) error); ok {
		r1 = returnFunc(context1, s, network)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackend_CreateNetwork_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateNetwork'
type MockBackend_CreateNetwork_Call struct {
	*mock.Call
}

// CreateNetwork is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - network compute.Network
func (_e *MockBackend_Expecter) CreateNetwork(context1 interface{}, s interface{}, network interface{}) *MockBackend_CreateNetwork_Call {
	return &MockBackend_CreateNetwork_Call{Call: _e.mock.On("CreateNetwork", context1, s, network)}
}

func (_c *MockBackend_CreateNetwork_Call) Run(run func(context1 context.Context, s string, network compute.Network)) *MockBackend_CreateNetwork_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 compute.Network
		if args[2] != nil {
			arg2 = args[2].(compute.Network)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBackend_CreateNetwork_Call) Return(network1 compute.Network, err error) *MockBackend_CreateNetwork_Call {
	_c.Call.Return(network1, err)
	return _c
}

func (_c *MockBackend_CreateNetwork_Call) RunAndReturn(run func(context1 context.Context, s string, network compute.Network) (compute.Network, error)) *MockBackend_CreateNetwork_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSandbox provides a mock function for the type MockBackend
func (_mock *MockBackend) CreateSandbox(context1 context.Context, sandbox compute.Sandbox) error {
	ret := _mock.Called(context1, sandbox)

	if len(ret) == 0 {
		panic("no return value specified for CreateSandbox")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, compute.Sandbox) error); ok {
		r0 = returnFunc(context1, sandbox)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBackend_CreateSandbox_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSandbox'
type MockBackend_CreateSandbox_Call struct {
	*mock.Call
}

// CreateSandbox is a helper method to define mock.On call
//   - context1 context.Context
//   - sandbox compute.Sandbox
func (_e *MockBackend_Expecter) CreateSandbox(context1 interface{}, sandbox interface{}) *MockBackend_CreateSandbox_Call {
	return &MockBackend_CreateSandbox_Call{Call: _e.mock.On("CreateSandbox", context1, sandbox)}
}

func (_c *MockBackend_CreateSandbox_Call) Run(run func(context1 context.Context, sandbox compute.Sandbox)) *MockBackend_CreateSandbox_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 compute.Sandbox
		if args[1] != nil {
			arg1 = args[1].(compute.Sandbox)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBackend_CreateSandbox_Call) Return(err error) *MockBackend_CreateSandbox_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBackend_CreateSandbox_Call) RunAndReturn(run func(context1 context.Context, sandbox compute.Sandbox) error) *MockBackend_CreateSandbox_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSnapshot provides a mock function for the type MockBackend
func (_mock *MockBackend) CreateSnapshot(context1 context.Context, ref compute.Ref, s string) error {
	ret := _mock.Called(context1, ref, s)

	if len(ret) == 0 {
		panic("no return value specified for CreateSnapshot")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, compute.Ref, string) error); ok {
		r0 = returnFunc(context1, ref, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBackend_CreateSnapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSnapshot'
type MockBackend_CreateSnapshot_Call struct {
	*mock.Call
}

// CreateSnapshot is a helper method to define mock.On call
//   - context1 context.Context
//   - ref compute.Ref
//   - s string
func (_e *MockBackend_Expecter) CreateSnapshot(context1 interface{}, ref interface{}, s interface{}) *MockBackend_CreateSnapshot_Call {
	return &MockBackend_CreateSnapshot_Call{Call: _e.mock.On("CreateSnapshot", context1, ref, s)}
}

func (_c *MockBackend_CreateSnapshot_Call) Run(run func(context1 context.Context, ref compute.Ref, s string)) *MockBackend_CreateSnapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 compute.Ref
		if args[1] != nil {
			arg1 = args[1].(compute.Ref)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBackend_CreateSnapshot_Call) Return(err error) *MockBackend_CreateSnapshot_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBackend_CreateSnapshot_Call) RunAndReturn(run func(context1 context.Context, ref compute.Ref, s string) error) *MockBackend_CreateSnapshot_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteFile provides a mock function for the type MockBackend
func (_mock *MockBackend) DeleteFile(context1 context.Context, ref compute.Ref, s string) error {
	ret := _mock.Called(context1, ref, s)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, compute.Ref, string) error); ok {
		r0 = returnFunc(context1, ref, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBackend_DeleteFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFile'
type MockBackend_DeleteFile_Call struct {
	*mock.Call
}

// DeleteFile is a helper method to define mock.On call
//   - context1 context.Context
//   - ref compute.Ref
//   - s string
func (_e *MockBackend_Expecter) DeleteFile(context1 interface{}, ref interface{}, s interface{}) *MockBackend_DeleteFile_Call {
	return &MockBackend_DeleteFile_Call{Call: _e.mock.On("DeleteFile", context1, ref, s)}
}

func (_c *MockBackend_DeleteFile_Call) Run(run func(context1 context.Context, ref compute.Ref, s string)) *MockBackend_DeleteFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 compute.Ref
		if args[1] != nil {
			arg1 = args[1].(compute.Ref)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBackend_DeleteFile_Call) Return(err error) *MockBackend_DeleteFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBackend_DeleteFile_Call) RunAndReturn(run func(context1 context.Context, ref compute.Ref, s string) error) *MockBackend_DeleteFile_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteInstance provides a mock function for the type MockBackend
func (_mock *MockBackend) DeleteInstance(context1 context.Context, ref compute.Ref) error {
	ret := _mock.Called(context1, ref)

	if len(ret) == 0 {
		panic("no return value specified for DeleteInstance")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, compute.Ref) error); ok {
		r0 = returnFunc(context1, ref)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBackend_DeleteInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteInstance'
type MockBackend_DeleteInstance_Call struct {
	*mock.Call
}

// DeleteInstance is a helper method to define mock.On call
//   - context1 context.Context
//   - ref compute.Ref
func (_e *MockBackend_Expecter) DeleteInstance(context1 interface{}, ref interface{}) *MockBackend_DeleteInstance_Call {
	return &MockBackend_DeleteInstance_Call{Call: _e.mock.On("DeleteInstance", context1, ref)}
}

func (_c *MockBackend_DeleteInstance_Call) Run(run func(context1 context.Context, ref compute.Ref)) *MockBackend_DeleteInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 compute.Ref
		if args[1] != nil {
			arg1 = args[1].(compute.Ref)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBackend_DeleteInstance_Call) Return(err error) *MockBackend_DeleteInstance_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBackend_DeleteInstance_Call) RunAndReturn(run func(context1 context.Context, ref compute.Ref) error) *MockBackend_DeleteInstance_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteNetwork provides a mock function for the type MockBackend
func (_mock *MockBackend) DeleteNetwork(context1 context.Context, s string, s1 string) error {
	ret := _mock.Called(context1, s, s1)

	if len(ret) == 0 {
		panic("no return value specified for DeleteNetwork")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(context1, s, s1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBackend_DeleteNetwork_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteNetwork'
type MockBackend_DeleteNetwork_Call struct {
	*mock.Call
}

// DeleteNetwork is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
func (_e *MockBackend_Expecter) DeleteNetwork(context1 interface{}, s interface{}, s1 interface{}) *MockBackend_DeleteNetwork_Call {
	return &MockBackend_DeleteNetwork_Call{Call: _e.mock.On("DeleteNetwork", context1, s, s1)}
}

func (_c *MockBackend_DeleteNetwork_Call) Run(run func(context1 context.Context, s string, s1 string)) *MockBackend_DeleteNetwork_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBackend_DeleteNetwork_Call) Return(err error) *MockBackend_DeleteNetwork_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBackend_DeleteNetwork_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string) error) *MockBackend_DeleteNetwork_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSandbox provides a mock function for the type MockBackend
func (_mock *MockBackend) DeleteSandbox(context1 context.Context, s string) error {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSandbox")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBackend_DeleteSandbox_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSandbox'
type MockBackend_DeleteSandbox_Call struct {
	*mock.Call
}

// DeleteSandbox is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockBackend_Expecter) DeleteSandbox(context1 interface{}, s interface{}) *MockBackend_DeleteSandbox_Call {
	return &MockBackend_DeleteSandbox_Call{Call: _e.mock.On("DeleteSandbox", context1, s)}
}

func (_c *MockBackend_DeleteSandbox_Call) Run(run func(context1 context.Context, s string)) *MockBackend_DeleteSandbox_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBackend_DeleteSandbox_Call) Return(err error) *MockBackend_DeleteSandbox_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBackend_DeleteSandbox_Call) RunAndReturn(run func(context1 context.Context, s string) error) *MockBackend_DeleteSandbox_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSnapshot provides a mock function for the type MockBackend
func (_mock *MockBackend) DeleteSnapshot(context1 context.Context, ref compute.Ref, s string) error {
	ret := _mock.Called(context1, ref, s)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSnapshot")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, compute.Ref, string) error); ok {
		r0 = returnFunc(context1, ref, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBackend_DeleteSnapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSnapshot'
type MockBackend_DeleteSnapshot_Call struct {
	*mock.Call
}

// DeleteSnapshot is a helper method to define mock.On call
//   - context1 context.Context
//   - ref compute.Ref
//   - s string
func (_e *MockBackend_Expecter) DeleteSnapshot(context1 interface{}, ref interface{}, s interface{}) *MockBackend_DeleteSnapshot_Call {
	return &MockBackend_DeleteSnapshot_Call{Call: _e.mock.On("DeleteSnapshot", context1, ref, s)}
}

func (_c *MockBackend_DeleteSnapshot_Call) Run(run func(context1 context.Context, ref compute.Ref, s string)) *MockBackend_DeleteSnapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 compute.Ref
		if args[1] != nil {
			arg1 = args[1].(compute.Ref)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBackend_DeleteSnapshot_Call) Return(err error) *MockBackend_DeleteSnapshot_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBackend_DeleteSnapshot_Call) RunAndReturn(run func(context1 context.Context, ref compute.Ref, s string) error) *MockBackend_DeleteSnapshot_Call {
	_c.Call.Return(run)
	return _c
}

// DetachNIC provides a mock function for the type MockBackend
func (_mock *MockBackend) DetachNIC(context1 context.Context, ref compute.Ref, s string) error {
	ret := _mock.Called(context1, ref, s)

	if len(ret) == 0 {
		panic("no return value specified for DetachNIC")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, compute.Ref, string) error); ok {
		r0 = returnFunc(context1, ref, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBackend_DetachNIC_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DetachNIC'
type MockBackend_DetachNIC_Call struct {
	*mock.Call
}

// DetachNIC is a helper method to define mock.On call
//   - context1 context.Context
//   - ref compute.Ref
//   - s string
func (_e *MockBackend_Expecter) DetachNIC(context1 interface{}, ref interface{}, s interface{}) *MockBackend_DetachNIC_Call {
	return &MockBackend_DetachNIC_Call{Call: _e.mock.On("DetachNIC", context1, ref, s)}
}

func (_c *MockBackend_DetachNIC_Call) Run(run func(context1 context.Context, ref compute.Ref, s string)) *MockBackend_DetachNIC_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 compute.Ref
		if args[1] != nil {
			arg1 = args[1].(compute.Ref)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBackend_DetachNIC_Call) Return(err error) *MockBackend_DetachNIC_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBackend_DetachNIC_Call) RunAndReturn(run func(context1 context.Context, ref compute.Ref, s string) error) *MockBackend_DetachNIC_Call {
	_c.Call.Return(run)
	return _c
}

// Exec provides a mock function for the type MockBackend
func (_mock *MockBackend) Exec(context1 context.Context, execRequest compute.ExecRequest, writer io.Writer, writer1 io.Writer) (int64, error) {
	ret := _mock.Called(context1, execRequest, writer, writer1)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, compute.ExecRequest, io.Writer, io.Writer) (int64, error)); ok {
		return returnFunc(context1, execRequest, writer, writer1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, compute.ExecRequest, io.Writer, io.Writer) int64); ok {
		r0 = returnFunc(context1, execRequest, writer, writer1)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, compute.ExecRequest, io.Writer, io.Writer) error); ok {
		r1 = returnFunc(context1, execRequest, writer, writer1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackend_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockBackend_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - context1 context.Context
//   - execRequest compute.ExecRequest
//   - writer io.Writer
//   - writer1 io.Writer
func (_e *MockBackend_Expecter) Exec(context1 interface{}, execRequest interface{}, writer interface{}, writer1 interface{}) *MockBackend_Exec_Call {
	return &MockBackend_Exec_Call{Call: _e.mock.On("Exec", context1, execRequest, writer, writer1)}
}

func (_c *MockBackend_Exec_Call) Run(run func(context1 context.Context, execRequest compute.ExecRequest, writer io.Writer, writer1 io.Writer)) *MockBackend_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 compute.ExecRequest
		if args[1] != nil {
			arg1 = args[1].(compute.ExecRequest)
		}
		var arg2 io.Writer
		if args[2] != nil {
			arg2 = args[2].(io.Writer)
		}
		var arg3 io.Writer
		if args[3] != nil {
			arg3 = args[3].(io.Writer)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockBackend_Exec_Call) Return(n int64, err error) *MockBackend_Exec_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockBackend_Exec_Call) RunAndReturn(run func(context1 context.Context, execRequest compute.ExecRequest, writer io.Writer, writer1 io.Writer) (int64, error)) *MockBackend_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// ExtendSandbox provides a mock function for the type MockBackend
func (_mock *MockBackend) ExtendSandbox(context1 context.Context, s string, time1 time.Time) (compute.Sandbox, error) {
	ret := _mock.Called(context1, s, time1)

	if len(ret) == 0 {
		panic("no return value specified for ExtendSandbox")
	}

	var r0 compute.Sandbox
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) (compute.Sandbox, error)); ok {
		return returnFunc(context1, s, time1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) compute.Sandbox); ok {
		r0 = returnFunc(context1, s, time1)
	} else {
		r0 = ret.Get(0).(compute.Sandbox)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = returnFunc(context1, s, time1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackend_ExtendSandbox_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExtendSandbox'
type MockBackend_ExtendSandbox_Call struct {
	*mock.Call
}

// ExtendSandbox is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - time1 time.Time
func (_e *MockBackend_Expecter) ExtendSandbox(context1 interface{}, s interface{}, time1 interface{}) *MockBackend_ExtendSandbox_Call {
	return &MockBackend_ExtendSandbox_Call{Call: _e.mock.On("ExtendSandbox", context1, s, time1)}
}

func (_c *MockBackend_ExtendSandbox_Call) Run(run func(context1 context.Context, s string, time1 time.Time)) *MockBackend_ExtendSandbox_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBackend_ExtendSandbox_Call) Return(sandbox compute.Sandbox, err error) *MockBackend_ExtendSandbox_Call {
	_c.Call.Return(sandbox, err)
	return _c
}

func (_c *MockBackend_ExtendSandbox_Call) RunAndReturn(run func(context1 context.Context, s string, time1 time.Time) (compute.Sandbox, error)) *MockBackend_ExtendSandbox_Call {
	_c.Call.Return(run)
	return _c
}

// GetInstance provides a mock function for the type MockBackend
func (_mock *MockBackend) GetInstance(context1 context.Context, ref compute.Ref) (compute.Instance, error) {
	ret := _mock.Called(context1, ref)

	if len(ret) == 0 {
		panic("no return value specified for GetInstance")
	}

	var r0 compute.Instance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, compute.Ref) (compute.Instance, error)); ok {
		return returnFunc(context1, ref)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, compute.Ref) compute.Instance); ok {
		r0 = returnFunc(context1, ref)
	} else {
		r0 = ret.Get(0).(compute.Instance)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, compute.Ref) error); ok {
		r1 = returnFunc(context1, ref)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackend_GetInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInstance'
type MockBackend_GetInstance_Call struct {
	*mock.Call
}

// GetInstance is a helper method to define mock.On call
//   - context1 context.Context
//   - ref compute.Ref
func (_e *MockBackend_Expecter) GetInstance(context1 interface{}, ref interface{}) *MockBackend_GetInstance_Call {
	return &MockBackend_GetInstance_Call{Call: _e.mock.On("GetInstance", context1, ref)}
}

func (_c *MockBackend_GetInstance_Call) Run(run func(context1 context.Context, ref compute.Ref)) *MockBackend_GetInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 compute.Ref
		if args[1] != nil {
			arg1 = args[1].(compute.Ref)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBackend_GetInstance_Call) Return(instance compute.Instance, err error) *MockBackend_GetInstance_Call {
	_c.Call.Return(instance, err)
	return _c
}

func (_c *MockBackend_GetInstance_Call) RunAndReturn(run func(context1 context.Context, ref compute.Ref) (compute.Instance, error)) *MockBackend_GetInstance_Call {
	_c.Call.Return(run)
	return _c
}

// GetNetwork provides a mock function for the type MockBackend
func (_mock *MockBackend) GetNetwork(context1 context.Context, s string, s1 string) (compute.Network, error) {
	ret := _mock.Called(context1, s, s1)

	if len(ret) == 0 {
		panic("no return value specified for GetNetwork")
	}

	var r0 compute.Network
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (compute.Network, error)); ok {
		return returnFunc(context1, s, s1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) compute.Network); ok {
		r0 = returnFunc(context1, s, s1)
	} else {
		r0 = ret.Get(0).(compute.Network)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(context1, s, s1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackend_GetNetwork_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNetwork'
type MockBackend_GetNetwork_Call struct {
	*mock.Call
}

// GetNetwork is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
func (_e *MockBackend_Expecter) GetNetwork(context1 interface{}, s interface{}, s1 interface{}) *MockBackend_GetNetwork_Call {
	return &MockBackend_GetNetwork_Call{Call: _e.mock.On("GetNetwork", context1, s, s1)}
}

func (_c *MockBackend_GetNetwork_Call) Run(run func(context1 context.Context, s string, s1 string)) *MockBackend_GetNetwork_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBackend_GetNetwork_Call) Return(network compute.Network, err error) *MockBackend_GetNetwork_Call {
	_c.Call.Return(network, err)
	return _c
}

func (_c *MockBackend_GetNetwork_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string) (compute.Network, error)) *MockBackend_GetNetwork_Call {
	_c.Call.Return(run)
	return _c
}

// GetSandbox provides a mock function for the type MockBackend
func (_mock *MockBackend) GetSandbox(context1 context.Context, s string) (compute.Sandbox, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for GetSandbox")
	}

	var r0 compute.Sandbox
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (compute.Sandbox, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) compute.Sandbox); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Get(0).(compute.Sandbox)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackend_GetSandbox_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSandbox'
type MockBackend_GetSandbox_Call struct {
	*mock.Call
}

// GetSandbox is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockBackend_Expecter) GetSandbox(context1 interface{}, s interface{}) *MockBackend_GetSandbox_Call {
	return &MockBackend_GetSandbox_Call{Call: _e.mock.On("GetSandbox", context1, s)}
}

func (_c *MockBackend_GetSandbox_Call) Run(run func(context1 context.Context, s string)) *MockBackend_GetSandbox_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBackend_GetSandbox_Call) Return(sandbox compute.Sandbox, err error) *MockBackend_GetSandbox_Call {
	_c.Call.Return(sandbox, err)
	return _c
}

func (_c *MockBackend_GetSandbox_Call) RunAndReturn(run func(context1 context.Context, s string) (compute.Sandbox, error)) *MockBackend_GetSandbox_Call {
	_c.Call.Return(run)
	return _c
}

// GetSandboxImage provides a mock function for the type MockBackend
func (_mock *MockBackend) GetSandboxImage(context1 context.Context, s string, s1 string) (compute.CatalogImage, error) {
	ret := _mock.Called(context1, s, s1)

	if len(ret) == 0 {
		panic("no return value specified for GetSandboxImage")
	}

	var r0 compute.CatalogImage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (compute.CatalogImage, error)); ok {
		return returnFunc(context1, s, s1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) compute.CatalogImage); ok {
		r0 = returnFunc(context1, s, s1)
	} else {
		r0 = ret.Get(0).(compute.CatalogImage)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(context1, s, s1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackend_GetSandboxImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSandboxImage'
type MockBackend_GetSandboxImage_Call struct {
	*mock.Call
}

// GetSandboxImage is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
func (_e *MockBackend_Expecter) GetSandboxImage(context1 interface{}, s interface{}, s1 interface{}) *MockBackend_GetSandboxImage_Call {
	return &MockBackend_GetSandboxImage_Call{Call: _e.mock.On("GetSandboxImage", context1, s, s1)}
}

func (_c *MockBackend_GetSandboxImage_Call) Run(run func(context1 context.Context, s string, s1 string)) *MockBackend_GetSandboxImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBackend_GetSandboxImage_Call) Return(catalogImage compute.CatalogImage, err error) *MockBackend_GetSandboxImage_Call {
	_c.Call.Return(catalogImage, err)
	return _c
}

func (_c *MockBackend_GetSandboxImage_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string) (compute.CatalogImage, error)) *MockBackend_GetSandboxImage_Call {
	_c.Call.Return(run)
	return _c
}

// InstanceForward provides a mock function for the type MockBackend
func (_mock *MockBackend) InstanceForward(context1 context.Context, ref compute.Ref, n int64, s string) (compute.Forward, error) {
	ret := _mock.Called(context1, ref, n, s)

	if len(ret) == 0 {
		panic("no return value specified for InstanceForward")
	}

	var r0 compute.Forward
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, compute.Ref, int64, string) (compute.Forward, error)); ok {
		return returnFunc(context1, ref, n, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, compute.Ref, int64, string) compute.Forward); ok {
		r0 = returnFunc(context1, ref, n, s)
	} else {
		r0 = ret.Get(0).(compute.Forward)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, compute.Ref, int64, string) error); ok {
		r1 = returnFunc(context1, ref, n, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackend_InstanceForward_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InstanceForward'
type MockBackend_InstanceForward_Call struct {
	*mock.Call
}

// InstanceForward is a helper method to define mock.On call
//   - context1 context.Context
//   - ref compute.Ref
//   - n int64
//   - s string
func (_e *MockBackend_Expecter) InstanceForward(context1 interface{}, ref interface{}, n interface{}, s interface{}) *MockBackend_InstanceForward_Call {
	return &MockBackend_InstanceForward_Call{Call: _e.mock.On("InstanceForward", context1, ref, n, s)}
}

func (_c *MockBackend_InstanceForward_Call) Run(run func(context1 context.Context, ref compute.Ref, n int64, s string)) *MockBackend_InstanceForward_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 compute.Ref
		if args[1] != nil {
			arg1 = args[1].(compute.Ref)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockBackend_InstanceForward_Call) Return(forward compute.Forward, err error) *MockBackend_InstanceForward_Call {
	_c.Call.Return(forward, err)
	return _c
}

func (_c *MockBackend_InstanceForward_Call) RunAndReturn(run func(context1 context.Context, ref compute.Ref, n int64, s string) (compute.Forward, error)) *MockBackend_InstanceForward_Call {
	_c.Call.Return(run)
	return _c
}

// ListInstances provides a mock function for the type MockBackend
func (_mock *MockBackend) ListInstances(context1 context.Context, s string) ([]compute.Instance, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for ListInstances")
	}

	var r0 []compute.Instance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]compute.Instance, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []compute.Instance); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]compute.Instance)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackend_ListInstances_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListInstances'
type MockBackend_ListInstances_Call struct {
	*mock.Call
}

// ListInstances is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockBackend_Expecter) ListInstances(context1 interface{}, s interface{}) *MockBackend_ListInstances_Call {
	return &MockBackend_ListInstances_Call{Call: _e.mock.On("ListInstances", context1, s)}
}

func (_c *MockBackend_ListInstances_Call) Run(run func(context1 context.Context, s string)) *MockBackend_ListInstances_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBackend_ListInstances_Call) Return(instances []compute.Instance, err error) *MockBackend_ListInstances_Call {
	_c.Call.Return(instances, err)
	return _c
}

func (_c *MockBackend_ListInstances_Call) RunAndReturn(run func(context1 context.Context, s string) ([]compute.Instance, error)) *MockBackend_ListInstances_Call {
	_c.Call.Return(run)
	return _c
}

// ListNetworks provides a mock function for the type MockBackend
func (_mock *MockBackend) ListNetworks(context1 context.Context, s string) ([]compute.Network, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for ListNetworks")
	}

	var r0 []compute.Network
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]compute.Network, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []compute.Network); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]compute.Network)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackend_ListNetworks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListNetworks'
type MockBackend_ListNetworks_Call struct {
	*mock.Call
}

// ListNetworks is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockBackend_Expecter) ListNetworks(context1 interface{}, s interface{}) *MockBackend_ListNetworks_Call {
	return &MockBackend_ListNetworks_Call{Call: _e.mock.On("ListNetworks", context1, s)}
}

func (_c *MockBackend_ListNetworks_Call) Run(run func(context1 context.Context, s string)) *MockBackend_ListNetworks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBackend_ListNetworks_Call) Return(networks []compute.Network, err error) *MockBackend_ListNetworks_Call {
	_c.Call.Return(networks, err)
	return _c
}

func (_c *MockBackend_ListNetworks_Call) RunAndReturn(run func(context1 context.Context, s string) ([]compute.Network, error)) *MockBackend_ListNetworks_Call {
	_c.Call.Return(run)
	return _c
}

// ListSandboxes provides a mock function for the type MockBackend
func (_mock *MockBackend) ListSandboxes(context1 context.Context) ([]compute.Sandbox, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for ListSandboxes")
	}

	var r0 []compute.Sandbox
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]compute.Sandbox, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []compute.Sandbox); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]compute.Sandbox)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackend_ListSandboxes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSandboxes'
type MockBackend_ListSandboxes_Call struct {
	*mock.Call
}

// ListSandboxes is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockBackend_Expecter) ListSandboxes(context1 interface{}) *MockBackend_ListSandboxes_Call {
	return &MockBackend_ListSandboxes_Call{Call: _e.mock.On("ListSandboxes", context1)}
}

func (_c *MockBackend_ListSandboxes_Call) Run(run func(context1 context.Context)) *MockBackend_ListSandboxes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBackend_ListSandboxes_Call) Return(sandboxs []compute.Sandbox, err error) *MockBackend_ListSandboxes_Call {
	_c.Call.Return(sandboxs, err)
	return _c
}

func (_c *MockBackend_ListSandboxes_Call) RunAndReturn(run func(context1 context.Context) ([]compute.Sandbox, error)) *MockBackend_ListSandboxes_Call {
	_c.Call.Return(run)
	return _c
}

// ListSnapshots provides a mock function for the type MockBackend
func (_mock *MockBackend) ListSnapshots(context1 context.Context, ref compute.Ref) ([]compute.Snapshot, error) {
	ret := _mock.Called(context1, ref)

	if len(ret) == 0 {
		panic("no return value specified for ListSnapshots")
	}

	var r0 []compute.Snapshot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, compute.Ref) ([]compute.Snapshot, error)); ok {
		return returnFunc(context1, ref)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, compute.Ref) []compute.Snapshot); ok {
		r0 = returnFunc(context1, ref)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]compute.Snapshot)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, compute.Ref) error); ok {
		r1 = returnFunc(context1, ref)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackend_ListSnapshots_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSnapshots'
type MockBackend_ListSnapshots_Call struct {
	*mock.Call
}

// ListSnapshots is a helper method to define mock.On call
//   - context1 context.Context
//   - ref compute.Ref
func (_e *MockBackend_Expecter) ListSnapshots(context1 interface{}, ref interface{}) *MockBackend_ListSnapshots_Call {
	return &MockBackend_ListSnapshots_Call{Call: _e.mock.On("ListSnapshots", context1, ref)}
}

func (_c *MockBackend_ListSnapshots_Call) Run(run func(context1 context.Context, ref compute.Ref)) *MockBackend_ListSnapshots_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 compute.Ref
		if args[1] != nil {
			arg1 = args[1].(compute.Ref)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBackend_ListSnapshots_Call) Return(snapshots []compute.Snapshot, err error) *MockBackend_ListSnapshots_Call {
	_c.Call.Return(snapshots, err)
	return _c
}

func (_c *MockBackend_ListSnapshots_Call) RunAndReturn(run func(context1 context.Context, ref compute.Ref) ([]compute.Snapshot, error)) *MockBackend_ListSnapshots_Call {
	_c.Call.Return(run)
	return _c
}

// OpenExec provides a mock function for the type MockBackend
func (_mock *MockBackend) OpenExec(context1 context.Context, execRequest compute.ExecRequest) (io.ReadWriteCloser, error) {
	ret := _mock.Called(context1, execRequest)

	if len(ret) == 0 {
		panic("no return value specified for OpenExec")
	}

	var r0 io.ReadWriteCloser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, compute.ExecRequest) (io.ReadWriteCloser, error)); ok {
		return returnFunc(context1, execRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, compute.ExecRequest) io.ReadWriteCloser); ok {
		r0 = returnFunc(context1, execRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadWriteCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, compute.ExecRequest) error); ok {
		r1 = returnFunc(context1, execRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackend_OpenExec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenExec'
type MockBackend_OpenExec_Call struct {
	*mock.Call
}

// OpenExec is a helper method to define mock.On call
//   - context1 context.Context
//   - execRequest compute.ExecRequest
func (_e *MockBackend_Expecter) OpenExec(context1 interface{}, execRequest interface{}) *MockBackend_OpenExec_Call {
	return &MockBackend_OpenExec_Call{Call: _e.mock.On("OpenExec", context1, execRequest)}
}

func (_c *MockBackend_OpenExec_Call) Run(run func(context1 context.Context, execRequest compute.ExecRequest)) *MockBackend_OpenExec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 compute.ExecRequest
		if args[1] != nil {
			arg1 = args[1].(compute.ExecRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBackend_OpenExec_Call) Return(readWriteCloser io.ReadWriteCloser, err error) *MockBackend_OpenExec_Call {
	_c.Call.Return(readWriteCloser, err)
	return _c
}

func (_c *MockBackend_OpenExec_Call) RunAndReturn(run func(context1 context.Context, execRequest compute.ExecRequest) (io.ReadWriteCloser, error)) *MockBackend_OpenExec_Call {
	_c.Call.Return(run)
	return _c
}

// PeerNetworks provides a mock function for the type MockBackend
func (_mock *MockBackend) PeerNetworks(context1 context.Context, s string, s1 string, s2 string) error {
	ret := _mock.Called(context1, s, s1, s2)

	if len(ret) == 0 {
		panic("no return value specified for PeerNetworks")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(context1, s, s1, s2)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBackend_PeerNetworks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PeerNetworks'
type MockBackend_PeerNetworks_Call struct {
	*mock.Call
}

// PeerNetworks is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
//   - s2 string
func (_e *MockBackend_Expecter) PeerNetworks(context1 interface{}, s interface{}, s1 interface{}, s2 interface{}) *MockBackend_PeerNetworks_Call {
	return &MockBackend_PeerNetworks_Call{Call: _e.mock.On("PeerNetworks", context1, s, s1, s2)}
}

func (_c *MockBackend_PeerNetworks_Call) Run(run func(context1 context.Context, s string, s1 string, s2 string)) *MockBackend_PeerNetworks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockBackend_PeerNetworks_Call) Return(err error) *MockBackend_PeerNetworks_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBackend_PeerNetworks_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string, s2 string) error) *MockBackend_PeerNetworks_Call {
	_c.Call.Return(run)
	return _c
}

// PublishInstance provides a mock function for the type MockBackend
func (_mock *MockBackend) PublishInstance(context1 context.Context, ref compute.Ref, s string) (string, error) {
	ret := _mock.Called(context1, ref, s)

	if len(ret) == 0 {
		panic("no return value specified for PublishInstance")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, compute.Ref, string) (string, error)); ok {
		return returnFunc(context1, ref, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, compute.Ref, string) string); ok {
		r0 = returnFunc(context1, ref, s)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, compute.Ref, string) error); ok {
		r1 = returnFunc(context1, ref, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackend_PublishInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishInstance'
type MockBackend_PublishInstance_Call struct {
	*mock.Call
}

// PublishInstance is a helper method to define mock.On call
//   - context1 context.Context
//   - ref compute.Ref
//   - s string
func (_e *MockBackend_Expecter) PublishInstance(context1 interface{}, ref interface{}, s interface{}) *MockBackend_PublishInstance_Call {
	return &MockBackend_PublishInstance_Call{Call: _e.mock.On("PublishInstance", context1, ref, s)}
}

func (_c *MockBackend_PublishInstance_Call) Run(run func(context1 context.Context, ref compute.Ref, s string)) *MockBackend_PublishInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 compute.Ref
		if args[1] != nil {
			arg1 = args[1].(compute.Ref)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBackend_PublishInstance_Call) Return(s1 string, err error) *MockBackend_PublishInstance_Call {
	_c.Call.Return(s1, err)
	return _c
}

func (_c *MockBackend_PublishInstance_Call) RunAndReturn(run func(context1 context.Context, ref compute.Ref, s string) (string, error)) *MockBackend_PublishInstance_Call {
	_c.Call.Return(run)
	return _c
}

// ReadBinaryFile provides a mock function for the type MockBackend
func (_mock *MockBackend) ReadBinaryFile(context1 context.Context, ref compute.Ref, s string) (io.ReadCloser, error) {
	ret := _mock.Called(context1, ref, s)

	if len(ret) == 0 {
		panic("no return value specified for ReadBinaryFile")
	}

	var r0 io.ReadCloser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, compute.Ref, string) (io.ReadCloser, error)); ok {
		return returnFunc(context1, ref, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, compute.Ref, string) io.ReadCloser); ok {
		r0 = returnFunc(context1, ref, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, compute.Ref, string) error); ok {
		r1 = returnFunc(context1, ref, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackend_ReadBinaryFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadBinaryFile'
type MockBackend_ReadBinaryFile_Call struct {
	*mock.Call
}

// ReadBinaryFile is a helper method to define mock.On call
//   - context1 context.Context
//   - ref compute.Ref
//   - s string
func (_e *MockBackend_Expecter) ReadBinaryFile(context1 interface{}, ref interface{}, s interface{}) *MockBackend_ReadBinaryFile_Call {
	return &MockBackend_ReadBinaryFile_Call{Call: _e.mock.On("ReadBinaryFile", context1, ref, s)}
}

func (_c *MockBackend_ReadBinaryFile_Call) Run(run func(context1 context.Context, ref compute.Ref, s string)) *MockBackend_ReadBinaryFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 compute.Ref
		if args[1] != nil {
			arg1 = args[1].(compute.Ref)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBackend_ReadBinaryFile_Call) Return(readCloser io.ReadCloser, err error) *MockBackend_ReadBinaryFile_Call {
	_c.Call.Return(readCloser, err)
	return _c
}

func (_c *MockBackend_ReadBinaryFile_Call) RunAndReturn(run func(context1 context.Context, ref compute.Ref, s string) (io.ReadCloser, error)) *MockBackend_ReadBinaryFile_Call {
	_c.Call.Return(run)
	return _c
}

// ReadFile provides a mock function for the type MockBackend
func (_mock *MockBackend) ReadFile(context1 context.Context, fileReadRequest compute.FileReadRequest) (compute.FileReadResult, error) {
	ret := _mock.Called(context1, fileReadRequest)

	if len(ret) == 0 {
		panic("no return value specified for ReadFile")
	}

	var r0 compute.FileReadResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, compute.FileReadRequest) (compute.FileReadResult, error)); ok {
		return returnFunc(context1, fileReadRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, compute.FileReadRequest) compute.FileReadResult); ok {
		r0 = returnFunc(context1, fileReadRequest)
	} else {
		r0 = ret.Get(0).(compute.FileReadResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, compute.FileReadRequest) error); ok {
		r1 = returnFunc(context1, fileReadRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackend_ReadFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadFile'
type MockBackend_ReadFile_Call struct {
	*mock.Call
}

// ReadFile is a helper method to define mock.On call
//   - context1 context.Context
//   - fileReadRequest compute.FileReadRequest
func (_e *MockBackend_Expecter) ReadFile(context1 interface{}, fileReadRequest interface{}) *MockBackend_ReadFile_Call {
	return &MockBackend_ReadFile_Call{Call: _e.mock.On("ReadFile", context1, fileReadRequest)}
}

func (_c *MockBackend_ReadFile_Call) Run(run func(context1 context.Context, fileReadRequest compute.FileReadRequest)) *MockBackend_ReadFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 compute.FileReadRequest
		if args[1] != nil {
			arg1 = args[1].(compute.FileReadRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBackend_ReadFile_Call) Return(fileReadResult compute.FileReadResult, err error) *MockBackend_ReadFile_Call {
	_c.Call.Return(fileReadResult, err)
	return _c
}

func (_c *MockBackend_ReadFile_Call) RunAndReturn(run func(context1 context.Context, fileReadRequest compute.FileReadRequest) (compute.FileReadResult, error)) *MockBackend_ReadFile_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveACLRule provides a mock function for the type MockBackend
func (_mock *MockBackend) RemoveACLRule(context1 context.Context, s string, s1 string, s2 string) error {
	ret := _mock.Called(context1, s, s1, s2)

	if len(ret) == 0 {
		panic("no return value specified for RemoveACLRule")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(context1, s, s1, s2)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBackend_RemoveACLRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveACLRule'
type MockBackend_RemoveACLRule_Call struct {
	*mock.Call
}

// RemoveACLRule is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
//   - s2 string
func (_e *MockBackend_Expecter) RemoveACLRule(context1 interface{}, s interface{}, s1 interface{}, s2 interface{}) *MockBackend_RemoveACLRule_Call {
	return &MockBackend_RemoveACLRule_Call{Call: _e.mock.On("RemoveACLRule", context1, s, s1, s2)}
}

func (_c *MockBackend_RemoveACLRule_Call) Run(run func(context1 context.Context, s string, s1 string, s2 string)) *MockBackend_RemoveACLRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockBackend_RemoveACLRule_Call) Return(err error) *MockBackend_RemoveACLRule_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBackend_RemoveACLRule_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string, s2 string) error) *MockBackend_RemoveACLRule_Call {
	_c.Call.Return(run)
	return _c
}

// RestartInstance provides a mock function for the type MockBackend
func (_mock *MockBackend) RestartInstance(context1 context.Context, ref compute.Ref, b bool) (compute.Instance, error) {
	ret := _mock.Called(context1, ref, b)

	if len(ret) == 0 {
		panic("no return value specified for RestartInstance")
	}

	var r0 compute.Instance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, compute.Ref, bool) (compute.Instance, error)); ok {
		return returnFunc(context1, ref, b)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, compute.Ref, bool) compute.Instance); ok {
		r0 = returnFunc(context1, ref, b)
	} else {
		r0 = ret.Get(0).(compute.Instance)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, compute.Ref, bool) error); ok {
		r1 = returnFunc(context1, ref, b)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackend_RestartInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestartInstance'
type MockBackend_RestartInstance_Call struct {
	*mock.Call
}

// RestartInstance is a helper method to define mock.On call
//   - context1 context.Context
//   - ref compute.Ref
//   - b bool
func (_e *MockBackend_Expecter) RestartInstance(context1 interface{}, ref interface{}, b interface{}) *MockBackend_RestartInstance_Call {
	return &MockBackend_RestartInstance_Call{Call: _e.mock.On("RestartInstance", context1, ref, b)}
}

func (_c *MockBackend_RestartInstance_Call) Run(run func(context1 context.Context, ref compute.Ref, b bool)) *MockBackend_RestartInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 compute.Ref
		if args[1] != nil {
			arg1 = args[1].(compute.Ref)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBackend_RestartInstance_Call) Return(instance compute.Instance, err error) *MockBackend_RestartInstance_Call {
	_c.Call.Return(instance, err)
	return _c
}

func (_c *MockBackend_RestartInstance_Call) RunAndReturn(run func(context1 context.Context, ref compute.Ref, b bool) (compute.Instance, error)) *MockBackend_RestartInstance_Call {
	_c.Call.Return(run)
	return _c
}

// RestoreSnapshot provides a mock function for the type MockBackend
func (_mock *MockBackend) RestoreSnapshot(context1 context.Context, ref compute.Ref, s string) error {
	ret := _mock.Called(context1, ref, s)

	if len(ret) == 0 {
		panic("no return value specified for RestoreSnapshot")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, compute.Ref, string) error); ok {
		r0 = returnFunc(context1, ref, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBackend_RestoreSnapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestoreSnapshot'
type MockBackend_RestoreSnapshot_Call struct {
	*mock.Call
}

// RestoreSnapshot is a helper method to define mock.On call
//   - context1 context.Context
//   - ref compute.Ref
//   - s string
func (_e *MockBackend_Expecter) RestoreSnapshot(context1 interface{}, ref interface{}, s interface{}) *MockBackend_RestoreSnapshot_Call {
	return &MockBackend_RestoreSnapshot_Call{Call: _e.mock.On("RestoreSnapshot", context1, ref, s)}
}

func (_c *MockBackend_RestoreSnapshot_Call) Run(run func(context1 context.Context, ref compute.Ref, s string)) *MockBackend_RestoreSnapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 compute.Ref
		if args[1] != nil {
			arg1 = args[1].(compute.Ref)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBackend_RestoreSnapshot_Call) Return(err error) *MockBackend_RestoreSnapshot_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBackend_RestoreSnapshot_Call) RunAndReturn(run func(context1 context.Context, ref compute.Ref, s string) error) *MockBackend_RestoreSnapshot_Call {
	_c.Call.Return(run)
	return _c
}

// StartInstance provides a mock function for the type MockBackend
func (_mock *MockBackend) StartInstance(context1 context.Context, ref compute.Ref, b bool) (compute.Instance, error) {
	ret := _mock.Called(context1, ref, b)

	if len(ret) == 0 {
		panic("no return value specified for StartInstance")
	}

	var r0 compute.Instance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, compute.Ref, bool) (compute.Instance, error)); ok {
		return returnFunc(context1, ref, b)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, compute.Ref, bool) compute.Instance); ok {
		r0 = returnFunc(context1, ref, b)
	} else {
		r0 = ret.Get(0).(compute.Instance)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, compute.Ref, bool) error); ok {
		r1 = returnFunc(context1, ref, b)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackend_StartInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartInstance'
type MockBackend_StartInstance_Call struct {
	*mock.Call
}

// StartInstance is a helper method to define mock.On call
//   - context1 context.Context
//   - ref compute.Ref
//   - b bool
func (_e *MockBackend_Expecter) StartInstance(context1 interface{}, ref interface{}, b interface{}) *MockBackend_StartInstance_Call {
	return &MockBackend_StartInstance_Call{Call: _e.mock.On("StartInstance", context1, ref, b)}
}

func (_c *MockBackend_StartInstance_Call) Run(run func(context1 context.Context, ref compute.Ref, b bool)) *MockBackend_StartInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 compute.Ref
		if args[1] != nil {
			arg1 = args[1].(compute.Ref)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBackend_StartInstance_Call) Return(instance compute.Instance, err error) *MockBackend_StartInstance_Call {
	_c.Call.Return(instance, err)
	return _c
}

func (_c *MockBackend_StartInstance_Call) RunAndReturn(run func(context1 context.Context, ref compute.Ref, b bool) (compute.Instance, error)) *MockBackend_StartInstance_Call {
	_c.Call.Return(run)
	return _c
}

// StopInstance provides a mock function for the type MockBackend
func (_mock *MockBackend) StopInstance(context1 context.Context, ref compute.Ref, b bool) (compute.Instance, error) {
	ret := _mock.Called(context1, ref, b)

	if len(ret) == 0 {
		panic("no return value specified for StopInstance")
	}

	var r0 compute.Instance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, compute.Ref, bool) (compute.Instance, error)); ok {
		return returnFunc(context1, ref, b)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, compute.Ref, bool) compute.Instance); ok {
		r0 = returnFunc(context1, ref, b)
	} else {
		r0 = ret.Get(0).(compute.Instance)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, compute.Ref, bool) error); ok {
		r1 = returnFunc(context1, ref, b)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackend_StopInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopInstance'
type MockBackend_StopInstance_Call struct {
	*mock.Call
}

// StopInstance is a helper method to define mock.On call
//   - context1 context.Context
//   - ref compute.Ref
//   - b bool
func (_e *MockBackend_Expecter) StopInstance(context1 interface{}, ref interface{}, b interface{}) *MockBackend_StopInstance_Call {
	return &MockBackend_StopInstance_Call{Call: _e.mock.On("StopInstance", context1, ref, b)}
}

func (_c *MockBackend_StopInstance_Call) Run(run func(context1 context.Context, ref compute.Ref, b bool)) *MockBackend_StopInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 compute.Ref
		if args[1] != nil {
			arg1 = args[1].(compute.Ref)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBackend_StopInstance_Call) Return(instance compute.Instance, err error) *MockBackend_StopInstance_Call {
	_c.Call.Return(instance, err)
	return _c
}

func (_c *MockBackend_StopInstance_Call) RunAndReturn(run func(context1 context.Context, ref compute.Ref, b bool) (compute.Instance, error)) *MockBackend_StopInstance_Call {
	_c.Call.Return(run)
	return _c
}

// WaitInstance provides a mock function for the type MockBackend
func (_mock *MockBackend) WaitInstance(context1 context.Context, waitRequest compute.WaitRequest) (compute.WaitResult, error) {
	ret := _mock.Called(context1, waitRequest)

	if len(ret) == 0 {
		panic("no return value specified for WaitInstance")
	}

	var r0 compute.WaitResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, compute.WaitRequest) (compute.WaitResult, error)); ok {
		return returnFunc(context1, waitRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, compute.WaitRequest) compute.WaitResult); ok {
		r0 = returnFunc(context1, waitRequest)
	} else {
		r0 = ret.Get(0).(compute.WaitResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, compute.WaitRequest) error); ok {
		r1 = returnFunc(context1, waitRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackend_WaitInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitInstance'
type MockBackend_WaitInstance_Call struct {
	*mock.Call
}

// WaitInstance is a helper method to define mock.On call
//   - context1 context.Context
//   - waitRequest compute.WaitRequest
func (_e *MockBackend_Expecter) WaitInstance(context1 interface{}, waitRequest interface{}) *MockBackend_WaitInstance_Call {
	return &MockBackend_WaitInstance_Call{Call: _e.mock.On("WaitInstance", context1, waitRequest)}
}

func (_c *MockBackend_WaitInstance_Call) Run(run func(context1 context.Context, waitRequest compute.WaitRequest)) *MockBackend_WaitInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 compute.WaitRequest
		if args[1] != nil {
			arg1 = args[1].(compute.WaitRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBackend_WaitInstance_Call) Return(waitResult compute.WaitResult, err error) *MockBackend_WaitInstance_Call {
	_c.Call.Return(waitResult, err)
	return _c
}

func (_c *MockBackend_WaitInstance_Call) RunAndReturn(run func(context1 context.Context, waitRequest compute.WaitRequest) (compute.WaitResult, error)) *MockBackend_WaitInstance_Call {
	_c.Call.Return(run)
	return _c
}

// WriteFile provides a mock function for the type MockBackend
func (_mock *MockBackend) WriteFile(context1 context.Context, fileWriteRequest compute.FileWriteRequest) (compute.FileWriteResult, error) {
	ret := _mock.Called(context1, fileWriteRequest)

	if len(ret) == 0 {
		panic("no return value specified for WriteFile")
	}

	var r0 compute.FileWriteResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, compute.FileWriteRequest) (compute.FileWriteResult, error)); ok {
		return returnFunc(context1, fileWriteRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, compute.FileWriteRequest) compute.FileWriteResult); ok {
		r0 = returnFunc(context1, fileWriteRequest)
	} else {
		r0 = ret.Get(0).(compute.FileWriteResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, compute.FileWriteRequest) error); ok {
		r1 = returnFunc(context1, fileWriteRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackend_WriteFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteFile'
type MockBackend_WriteFile_Call struct {
	*mock.Call
}

// WriteFile is a helper method to define mock.On call
//   - context1 context.Context
//   - fileWriteRequest compute.FileWriteRequest
func (_e *MockBackend_Expecter) WriteFile(context1 interface{}, fileWriteRequest interface{}) *MockBackend_WriteFile_Call {
	return &MockBackend_WriteFile_Call{Call: _e.mock.On("WriteFile", context1, fileWriteRequest)}
}

func (_c *MockBackend_WriteFile_Call) Run(run func(context1 context.Context, fileWriteRequest compute.FileWriteRequest)) *MockBackend_WriteFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 compute.FileWriteRequest
		if args[1] != nil {
			arg1 = args[1].(compute.FileWriteRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBackend_WriteFile_Call) Return(fileWriteResult compute.FileWriteResult, err error) *MockBackend_WriteFile_Call {
	_c.Call.Return(fileWriteResult, err)
	return _c
}

func (_c *MockBackend_WriteFile_Call) RunAndReturn(run func(context1 context.Context, fileWriteRequest compute.FileWriteRequest) (compute.FileWriteResult, error)) *MockBackend_WriteFile_Call {
	_c.Call.Return(run)
	return _c
}
