// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/GilmanLab/agentcompute/internal/compute"
)

// NewMockPendingInstance creates a new instance of MockPendingInstance. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPendingInstance(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPendingInstance {
	mock := &MockPendingInstance{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPendingInstance is an autogenerated mock type for the PendingInstance type
type MockPendingInstance struct {
	mock.Mock
}

type MockPendingInstance_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPendingInstance) EXPECT() *MockPendingInstance_Expecter {
	return &MockPendingInstance_Expecter{mock: &_m.Mock}
}

// Wait provides a mock function for the type MockPendingInstance
func (_mock *MockPendingInstance) Wait(context1 context.Context) (compute.Instance, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Wait")
	}

	var r0 compute.Instance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (compute.Instance, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) compute.Instance); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Get(0).(compute.Instance)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPendingInstance_Wait_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Wait'
type MockPendingInstance_Wait_Call struct {
	*mock.Call
}

// Wait is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockPendingInstance_Expecter) Wait(context1 interface{}) *MockPendingInstance_Wait_Call {
	return &MockPendingInstance_Wait_Call{Call: _e.mock.On("Wait", context1)}
}

func (_c *MockPendingInstance_Wait_Call) Run(run func(context1 context.Context)) *MockPendingInstance_Wait_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPendingInstance_Wait_Call) Return(instance compute.Instance, err error) *MockPendingInstance_Wait_Call {
	_c.Call.Return(instance, err)
	return _c
}

func (_c *MockPendingInstance_Wait_Call) RunAndReturn(run func(context1 context.Context) (compute.Instance, error)) *MockPendingInstance_Wait_Call {
	_c.Call.Return(run)
	return _c
}
